### ISSUE TITLE
ace-delete-(other)-window(s) choose wrong window when only two

### ISSUE THREAD

**Issue by mkrauss** [abo-abo/ace-window#100]
It seems that these functions:

ace-delete-window
ace-delete-other-windows

.. are choosing the wrong windows, in the case that there are only two windows available.

I would think that in this case they should work like the normal functions delete-window and delete-other-window, deleting the current window, or all windows but the current window, respectively. However, counter-intuitively, delete-window deletes the other window, and delete-other-windows deletes the current window.

Is this intentional?

I would swap the keys but then they would make no sense when there were more than two windows...

**Comment by abo-abo** [comment]
> Is this intentional?

Yes. `ace-window` aims to replace `other-window`. So it does works on other window intentionally.

**Comment by mkrauss** [comment]
I think there may be some misunderstanding. Certainly I understand that `ace-window` replaces `other-window`, and it makes sense for that function to choose the other window to switch to. However, `ace-delete-window` and `ace-delete-other-windows` cannot be replacing `other-window` since they do something completely different.

It is my understanding that `ace-delete-window` is replacing `delete-window` and `ace-delete-other-windows` is replacing `ace-delete-other-windows`. Is that not correct?

**Comment by abo-abo** [comment]
> It is my understanding that ace-delete-window is replacing delete-window and ace-delete-other-windows is replacing delete-other-windows. Is that not correct?

- `ace-delete-window` is `delete-window` from the context of `other-window`.
- `ace-delete-other-windows` is `delete-other-windows` from the context of `other-window`.

**Comment by dieggsy** [comment]
@abo-abo is there any chance of making this customizable? I would really expect ace-delete-window to delete the other window when there's only two visible.

**Comment by dieggsy** [comment]
Actually, I think I understand now. The two window behavior is more consistent with the multi-window behavior as it is now. I'll try to get used to this workflow.
