### ISSUE TITLE
A combination of ace-window and global-set-key and use-package cause corruption of behaviour of function, PageUp,  and PageDnkeys

### ISSUE THREAD

**Issue by vonHabsi** [abo-abo/ace-window#101]
When I try to run emacs in a terminal connection on a particular system the function and the page up and page down keys don't work correctly.

    F8 - No such candidate, 49
    F10 - No such candidate, 50
    F12 - No such candidate, 50
    
    Page down - No such candidate, 53
    Page up - No such candidate, 54
    
I traced it to a sequence in this use-package config. I changed the default `M-p` set by `ace-window` to `M-[` that is what causes it. I don't know whether it is in global-set-key itself, or the use in combination with `ace-window` and or `use-package` is the cause.

    (use-package ace-window
      :ensure t
      :defer t
      :init
      (progn
        (global-set-key (kbd "<f9>") 'ace-window)
        (global-set-key (kbd "M-[") 'ace-window)
        (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l))
        ;;more info at https://github.com/abo-abo/ace-window
        )
      )

**Comment by abo-abo** [comment]
So `M-p` works, but `M-[` doesn't. Looks like a teminal limitation; not connected to `ace-window`.

**Comment by vonHabsi** [comment]
Do you know of any escape sequence which could be triggered by applying  `M-[` to global-set-key?

Whatever happens I will try on the unix mailing lists. Thanks
