### ISSUE TITLE
Problem in README concerning `aw-dispatch-always`?

### ISSUE THREAD

**Issue by DamienCassou** [abo-abo/ace-window#102]
The README says:

> In order for it to work, these keys *must not* be in `aw-keys` and you have to have `aw-dispatch-always` set to `t`.

I think that "changing the action midway" (title of the README section) works whatever `aw-dispatch-always` value is as soon as there are more than 2 windows.

**Comment by abo-abo** [comment]
Could you open a PR with a rewording?
