### ISSUE TITLE
Pressing ? and then x gives back broken Emacs

### ISSUE THREAD

**Issue by DamienCassou** [abo-abo/ace-window#105]
1. start emacs -Q
2. evaluate the following in the scratch buffer
    ```emacs
    (require 'package)
    (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
    (package-initialize)
    (package-refresh-contents)
    (package-install 'ace-window)
    ```
3. Create some frames: `C-x 3 C-x 2`
3. Type `M-x ace-window RET ? x 2`

ace-windows is now terminated, but the Emacs syntax highlighting colors are not back:
![screenshot from 2017-11-09 06-58-58](https://user-images.githubusercontent.com/217543/32590621-880667ae-c51b-11e7-80ed-89c76cc09afc.png)

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by DamienCassou** [comment]
It works fine, thank you.
