### ISSUE TITLE
aw-switch-buffer-in-window and virtual buffers

### ISSUE THREAD

**Issue by woodensquares** [abo-abo/ace-window#107]
If virtual buffers are enabled and the user chooses a virtual buffer, this does not seem to work correctly (it creates an empty buffer named the selected virtual buffer name, rather than opening the corresponding file), changing switch-to-buffer to ivy-switch-buffer in aw-switch-buffer-in-window seems to solve this.

**Comment by abo-abo** [comment]
You're right. But `ace-window` doesn't assume that `ivy` is installed, so simply calling `aw-switch-buffer-in-window` isn't appropriate in case the user doesn't have ivy installed.
I might add a check for `ivy-mode` on, and then call `ivy-switch-buffer` after that.

**Comment by woodensquares** [comment]
yeah, I was wondering if you wanted to add a dependency on ivy or not, makes sense

**Comment by abo-abo** [comment]
Thanks.
