### ISSUE TITLE
Quitting out of dispatch list gives argument error

### ISSUE THREAD

**Issue by nsemrau** [abo-abo/ace-window#108]
### Situation

I launch `ace-window` while I have several buffer windows open. Then, pressing `?` shows me the dispatch list of possible keys for ace-window functions in the minibuffer.

### Problem

When I decide to quit out of ace-window with `C-g` at this point, I get a message reading `aw-dispatch-default: Wrong number of arguments: 0, nil`.

### Expected behaviour

ace-window quits without an argument error message.

**Comment by abo-abo** [comment]
Thanks.
