### ISSUE TITLE
[Feature request] Add some help when call ace-window

### ISSUE THREAD

**Issue by Postroutine** [abo-abo/ace-window#111]
When user call `ace-window` function, it would be cool to display a little help in the minibuffer.

For example: `Select a window [1--3] or an action, type [?] for help or [C-h i] show the manual`
And if user type `?`, a popup (like in magit) show all possibles actions with their corresponding key.

**Comment by abo-abo** [comment]
This was already added recently. Update and press <kbd>?</kbd>.

**Comment by Postroutine** [comment]
Maybe be a little more new friendly by adding this to minibuffer when user call `ace-window` function:
`Select a window [1--3] or an action, type [?] for help or [C-h i] show the manual` ?
