### ISSUE TITLE
Unhandled window target character triggers an error

### ISSUE THREAD

**Issue by rswgnu** [abo-abo/ace-window#119]
If M-o is bound to ace-window, then M-o RET triggers this error:

Debugger entered--Lisp error: (wrong-number-of-arguments nil 0)
  signal(wrong-number-of-arguments (nil 0))
  aw-dispatch-default(13)
  avy-read(((97 leaf 6882 . #<window 3 on ace-window.el<ace-window>>) (115 leaf 371862 . #<window 12 on *Packages*>) (100 leaf 4491 . #<window 14 on ace-window.el<ace-window-20171209.751>>) (102 leaf 1 . #<window 20 on *Backtrace*>)) aw--lead-overlay avy--remove-leading-chars)
  aw-select(" Ace - Window" aw-switch-to-window)
  ace-select-window()
  ace-window(1)
  funcall-interactively(ace-window 1)
  call-interactively(ace-window nil nil)
  command-execute(ace-window)

-----
This is due to the cl-destructuring-bind in aw-dispatch-default not handling this.  I have previously offered a fix for this.

**Comment by abo-abo** [comment]
Fixed, thanks.

> aw-clean-up-avy-current-path

Any reproduction scenario for when this is useful?

**Comment by rswgnu** [comment]
On Mon, Dec 11, 2017 at 12:13 PM, Oleh Krehel <notifications@github.com>
wrote:

> Fixed, thanks.
>
> aw-clean-up-avy-current-path
>
> Any reproduction scenario for when this is useful?
>
​When using ace-window, if you want to test if a particular window was
selected, now you can.  I can provide more details later.
