### ISSUE TITLE
Large horizontal scroll causes error

### ISSUE THREAD

**Issue by holocronweaver** [abo-abo/ace-window#12]
When switching windows, occasionally the buffers darken yet no selection characters are displayed in them and hitting keys does nothing until I use C-g to escape ace-window.  

An error message appears in the modeline: `Args out of range: #<buffer *myBuffer*>, 1713, 1714`.

I believe this is referring to the horizontal scroll of `myBuffer` being too large for ace-window to handle.  This happens fairly often to me as I often am editing files with very long lines.

Afterwards the darkened buffers do not return to their original color, remaining dark.  I haven't found any way to undo the discoloration except restarting Emacs (reapplying major-mode does not help).  Might this discoloration be a failure state in ace-window that doesn't clean up after itself?

So the two bugs seem to be: 
1. Large horizontal scrolls cause ace-window to spit the above error message and fail to allow switching windows.
2. This failure results in windows remaining dark rather than reverting to original color.

**Comment by endrebak** [comment]
I'm getting the same behavior in an ipython interpreter.

Try to reproduce:

```
1. open ipython buffer
2. write globals()<RET> a couple of times to produce a lot of output.
3. press the ace-window command.
```

Now you should not see any selection letter in the ipython window. However, if you move up a few lines and try again the `ace-window` letter will show. If you move down again and try `ace-window` it won't work.

`24.5, OS X, latest ace-window probably (I always get the latest updates from paradox`.

Not expecting you to do anything about it, just reporting it in case you are interested.

**Comment by abo-abo** [comment]
> To reproduce:

The recipe doesn't provide the window configuration.  I opened 3 ipython windows, just it case, it works fine.

**Comment by endrebak** [comment]
Triple windows split vertically. Thanks, for checking, I guess it is just me then.

**Comment by abo-abo** [comment]
> Triple windows split vertically

Can't reproduce, with either graphical or `emacs -nw`. It could be OSX specific. If I could reproduce it on GNU/Linux, I'd probably be able to fix it.
