### ISSUE TITLE
Set leading char larger by default

### ISSUE THREAD

**Issue by stardiviner** [abo-abo/ace-window#120]
```elisp
(set-face-attribute 'aw-leading-char-face nil
                      :height 2.5 :weight 'bold)
```

**Comment by abo-abo** [comment]
I see how this can be useful, but it's a trade-off. By default, `ace-window` won't move your text around; with this change, it will.

So I think the defaults should remain the same in this case.

It's not difficult to make this customization in the user space, even possible via `customize`. If you want, add this code to [the wiki](https://github.com/abo-abo/ace-window/wiki) to give new users an idea of what to customize.
