### ISSUE TITLE
m-p used for previous-input

### ISSUE THREAD

**Issue by jave** [abo-abo/ace-window#123]
This is just a small documentation nit.
m-p is used for previous-input in shell-like buffers, so the binding is not always free. It might surprise new users trying out the library.

**Comment by abo-abo** [comment]
I see. Indeed, <kbd>M-p</kbd> is slightly problematic; I don't use this binding myself as well.

On the other hand, it's still better ergonomically than <kbd>C-x o</kbd>. And I think if I don't suggest any rebind the users will go for <kbd>C-x o</kbd>.

I'm open to suggestions, if you can propose something that's better than <kbd>M-p</kbd> or <kbd>C-x o</kbd>. There aren't many unbound two-key chords.

**Comment by jave** [comment]
I think it will suffice to say that M-p is used in shell buffers etc,
then the user will need to solve the problem by herself.

I like to use C-RET, but that doesnt work in terminals withouth
difficulty, so it sucks as well. M-o is okay as well, because there some
font functionality there I dont use. Some people like using key-chord.el
to get more possibilities.



Oleh Krehel <notifications@github.com> writes:

> I see. Indeed, M-p is slightly problematic; I don't use this binding myself as well.
>
> On the other hand, it's still better ergonomically than C-x o. And I think if I don't suggest any rebind the users will go for C-x o.
>
> I'm open to suggestions, if you can propose something that's better than M-p or C-x o. There aren't many unbound two-key chords.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
-- 
Joakim Verona
joakim@verona.se
+46705459454

**Comment by abo-abo** [comment]
Thanks.
