### ISSUE TITLE
Method with `aw-dispatch-always` enabled

### ISSUE THREAD

**Issue by To1ne** [abo-abo/ace-window#126]
In most cases I want `aw-dispatch-always` to be `nil`, but sometimes I want it to by `t`. So I decided to create a function:

```elisp
(defun my-ace-window-always ()
"Always dispatch to ace-window"
  (interactive)
  (let ((aw-dispatch-always t))
    (ace-window 0)))
```

And this works fine for switching windows. But when I try to use one of the keys in `aw-dispatch-alist` I am getting the error:

>avy-read: Wrong type argument: number-or-marker-p, nil

**Comment by To1ne** [comment]
OK, I'm having the same problem with _norma_ `ace-window` use now. So I probably misconfigured something. Let me get back to this later.

**Comment by To1ne** [comment]
I had `aw-make-frame-char` set to `nil`. Ace-window does not seem to like this.

Is there a way to disable the `aw-make-frame-char` functionality?

**Comment by abo-abo** [comment]
Pinging @rswgnu, the author of `aw-make-frame-char`.

**Comment by rswgnu** [comment]
What's up Oleh?

-- Bob

**Comment by To1ne** [comment]
@rswgnu Yeah, this issue changed it's intent along the way. My question was if it was possible to disable the functionality of `aw-make-frame-char` completely. Setting it to`nil` seems to cause trouble.

But it's really not a big issue, I just set it to `5`, which is far enough from my homerow and doesn't obstruct the keys in `aw-dispatch-alist`.

Although, one question, I don't really see why `aw-make-frame-char` is a separate feature from `aw-dispatch-alist`?
