### ISSUE TITLE
winner-redo error: previous comand was not a `winner-undo`

### ISSUE THREAD

**Issue by yiufung** [abo-abo/ace-window#130]
I copied the [last snippet](https://github.com/abo-abo/ace-window/wiki#manage-100-window-operations) at Wiki page to a vanilla Emacs 25.3.1, and saw the error from winner-redo. Looking around, it seems to be similar with [hydra#79](https://github.com/abo-abo/hydra/issues/79). So I changed the line for `winner-undo` to your advice

``` emacs-lisp
(?u (lambda () (progn (winner-undo) (setq this-command 'winner-undo))))
```

And it works. Can you see if this can be reproduced?

**Comment by abo-abo** [comment]
> And it works.

Thanks, I've modified the wiki page with your code.
