### ISSUE TITLE
Window numbers or characters are missing sometimes

### ISSUE THREAD

**Issue by seagle0128** [abo-abo/ace-window#131]
I love `ace-window`, but experiencing some issues. e.g. sometimes the window numbers are missing as the screenshot below (1 and 2 missing). After switch to other window, they may be displayed again. 

Another issue is the sequence of the window numbers are not always same as `window-numbering`. Any customization for that?

<img width="839" alt="screen shot 2018-05-29 at 12 36 35 am" src="https://user-images.githubusercontent.com/140797/40623266-8be6c052-62d8-11e8-8e62-6e9422ecb077.png">

**Comment by abo-abo** [comment]
Please give me a reproducible scenario for when there's no window number.

**Comment by seagle0128** [comment]
I don't know how to describe. These are my steps.

1. Open Emacs with `server-mode`.
1. `C-x 2` and `C-x 3` for couple of times.
1. `C-x o` to switch window.

That's all. Then you may see the window numbers are missing perhaps, not all the time.
I didn't figure out the pattern.

**Comment by seagle0128** [comment]
Update: I switch to `switch-window` a few days ago. In the same scenarios, it's stable and works well.

**Comment by abo-abo** [comment]
Hmm, I still can't do much without a reproduction scenario. Here's what I expect:

- Start `emacs -Q`
- Load only the necessary packages, e.g. `avy` and `ace-window`
- <kbd>C-x 2</kbd>, <kbd>C-x 3</kbd> etc.
- <kbd>M-x</kbd> `ace-window`, and the bug happens

If there's a repro scenario, I can actually debug the issue to see where it goes wrong. I can't do much by looking at a screenshot, and I don't want to debug all the package interactions in your config.

**Comment by seagle0128** [comment]
@abo-abo I found some clues. If I set faces of ace-window, it's easier to recreate the issue (but not 100%). Split more windows and try more times. 

```elisp
(custom-set-faces
   '(aw-leading-char-face
     ((t
       (:foreground "deep sky blue" :bold t :height 3.0)))))
```

**Comment by abo-abo** [comment]
I tried your `custom-set-faces`, I still can't reproduce. I'm sorry that you're getting an issue, but unless it's something reproducible I can't fix it.

**Comment by seagle0128** [comment]
It's easy to reproduce in my envs, including both macOS 10.13.5 and Ubuntu 18.04 LTS, with GNU Emacs 26.1. I believe the issue also exists on Emacs 25.3.

I made a recording here. You can see, after customizing faces, the character was missing, then came back. It's annoying! 
![ace-window1](https://user-images.githubusercontent.com/140797/42326757-a9200c1e-809c-11e8-8eff-d3c717f50055.gif)

**Comment by abo-abo** [comment]
> It's easy to reproduce in my envs

I still can't reproduce this. I tried `make plain` with your extra faces code, and splitting the windows the way you did.

I think in order to reproduce this more things are needed:

- example buffer contents
- precise frame geometry
- precise point and scroll state

**Comment by seagle0128** [comment]
Well, in my screen recording, `emacs -Q` to start the Emacs. Only one package `ace-window` is loaded. All codes are in the screen there. I attached below as well. 

At first, I didn't eval `custom-set-faces` snippet, the numbers were displayed correctly. Then changed the faces, the number 3 was missing. `C-x o` again, all numbers were showed.

```elisp
(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(setq package-archives '(("gnu"   . "http://elpa.gnu.org/packages/")
                         ("melpa" . "http://melpa.org/packages/")))

(package-initialize)

(require 'ace-window)
(global-set-key [remap other-window] 'ace-window)

(custom-set-faces
 '(aw-leading-char-face
   ((t
     (:foreground "deep sky blue" :bold t :height 3.0)))))
```

**Comment by abo-abo** [comment]
Can you also add your `(frame-parameters)` and the point position when you called `ace-window`. Maybe also the scroll amount if it matters.

**Comment by seagle0128** [comment]
I use this to get the information on Ubuntu 18.04.
GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-29
```elisp
(global-set-key [remap other-window]
                (lambda(arg)
		  (interactive "p")
                  (message "%s" (frame-parameters))
                  (ace-window arg)))
```
When the issue happened, the output is
```elisp
((parent-id . 16217870) (explicit-name) (display . :0) (icon-name) (outer-window-id . 71303491) (window-id . 71303495) (top . 132) (left . 912) (buried-buffer-list) (buffer-list *scratch*  *Minibuf-1* *Help*) (unsplittable) (modeline . t) (width . 80) (height . 36) (name . emacs@ubuntu) (environment) (sticky) (cursor-color . black) (background-mode . light) (display-type . color) (window-system . x) (z-group) (skip-taskbar) (visibility . t) (fullscreen) (no-accept-focus) (no-focus-on-map) (alpha) (scroll-bar-height . 0) (scroll-bar-width . 16) (cursor-type . box) (auto-lower) (auto-raise) (icon-type . t) (inhibit-double-buffering) (tool-bar-position . top) (wait-for-wm . t) (title) (buffer-predicate) (tool-bar-lines . 1) (menu-bar-lines . 1) (scroll-bar-background) (scroll-bar-foreground) (no-special-glyphs) (right-fringe . 8) (left-fringe . 8) (line-spacing) (screen-gamma) (border-color . black) (mouse-color . black) (background-color . white) (foreground-color . black) (horizontal-scroll-bars) (vertical-scroll-bars . right) (bottom-divider-width . 0) (right-divider-width . 0) (internal-border-width . 0) (border-width . 0) (font-parameter . Ubuntu Mono 13) (font . -DAMA-Ubuntu Mono-normal-normal-normal-*-17-*-*-*-m-0-iso10646-1) (font-backend xft x) (override-redirect) (undecorated) (parent-frame) (minibuffer . t))
```
![screenshot at 2018-07-06 11-40-49](https://user-images.githubusercontent.com/140797/42358885-851bb096-8111-11e8-95a0-135b1f4769c1.png)

**Comment by ofenerci** [comment]
I have Emacs 26.1 and the windows doesn't show the numbers at all.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by seagle0128** [comment]
The issue still exists with the latest version.

![image](https://user-images.githubusercontent.com/140797/51986693-c1d65e00-24db-11e9-9c45-d792e901b1de.png)

**Comment by abo-abo** [comment]
@seagle0128 Thanks, please test again.

**Comment by seagle0128** [comment]
It works and no issue found so far. Than you, @abo-abo !

**Comment by seagle0128** [comment]
Update: it seems the positions is below `top-left` now.

**Comment by abo-abo** [comment]
> Update: it seems the position is below top-left now.

That's the trade-off, unfortunately. It's a work-around of an Emacs display bug, where the overlay on the top line may not be displayed if it has a height bigger than the height of the top line.

Suggestions or patches for better work-arounds are welcome, but I think I can't do much more here as it is now.

**Comment by rswgnu** [comment]
I am using: Package-Version: 20190210.1648 and I still see this problem whenever the buffer in a window is horizontally scrolled so that the left-most characters are not visible.  ace-window should account for (window-hscroll) and place the leading-char within a visible part of the window.  Can that be done?

**Comment by rswgnu** [comment]
Here's a patch that I tested with 81 windows and it displayed the leading-char properly in all of them except buffers receiving output during the aw--lead-overlay function call since the output may scroll the overlay point outside the window's visible range, e.g. the *Messages* buffer.  Prior to this patch maybe 10% of the windows failed to display the overlay character; now it is closer to 1%.


[aw-diff.txt](https://github.com/abo-abo/ace-window/files/2872671/aw-diff.txt)
