### ISSUE TITLE
Window number missing in eshell 

### ISSUE THREAD

**Issue by emosesPatreon** [abo-abo/ace-window#134]
When I have a window showing an eshell buffer, the window number is missing. It shows up fine in other buffers.  Also, that window clearly has a number assigned; if I guess it correctly it works (e.g., if I have three windows open, one shows `1`, one shows `3`, and there's nothing in the eshell window, if I hit `2`, it jumps to eshell)

Emacs-version: GNU Emacs 26.1 (build 1, x86_64-apple-darwin17.5.0, Carbon Version 158 AppKit 1561.4) of 2018-05-29 (this is the Yamamoto mac port https://bitbucket.org/mituharu/emacs-mac/)

Ace-window: version 0.9.0

**Comment by abo-abo** [comment]
Can't reproduce on GNU Emacs 26.1 on Linux with the latest master.

**Comment by powellb** [comment]
I have the same issue; however, it does not happen using the standard gnu emacs 26.1. It does occur with Yamamoto's port, so I think the issue is likely some change/difference introduced in emacs-mac.

**Comment by ofenerci** [comment]
I have the same issue for Emacs 26

**Comment by seagle0128** [comment]
Same issue here. it's similar with #131, I think.

**Comment by abo-abo** [comment]
Please test.

**Comment by emosesPatreon** [comment]
Looks like it's working.  Thanks!

**Comment by IceAsteroid** [comment]
Setting *leading char* to a larger height causes the window number to not show accidentally in eshell if eshell is in a smaller window in height. Sometimes it shows up, sometimes it doesn't
