### ISSUE TITLE
How fast swap between buffers?

### ISSUE THREAD

**Issue by lmdic** [abo-abo/ace-window#139]
Windows 10, Emacs 25.1

I have 4 open buffers.

Here

![step_0](https://user-images.githubusercontent.com/303539/44298925-38e4b500-a2f5-11e8-8b82-7924554e2ab1.png)

To switch from buffer "**file_1.txt**" to buffer "**file_2.txt**" I use standard command `windmove-right.` It is bound to `<M-right>`. 

![step_1](https://user-images.githubusercontent.com/303539/44298934-4ef27580-a2f5-11e8-9864-c0b33b4acd2f.png)

To switch from buffer "**file_2.txt**" to buffer "**file_3.txt**" I use standard command `windmove-down`. It is bound to `<M-down>`.

And so on. It's very comfortable. Nice.

But what if I need to SWAP buffers "**file_1.txt**" and "**file_2.txt**"?

The result must be like this:

![step_2](https://user-images.githubusercontent.com/303539/44298938-587bdd80-a2f5-11e8-891a-054c4d746ff2.png)

To do this I use package `ace-window` and command `ace-swap-window`.

Here steps. 
1. Start command `ace-swap-window`

![step_3](https://user-images.githubusercontent.com/303539/44298940-63367280-a2f5-11e8-8f1b-439768cf5c5b.png)

Select number of windows I want to swap - "**3**" 
![step_4](https://user-images.githubusercontent.com/303539/44298943-6cbfda80-a2f5-11e8-8a52-9b6161c79d6f.png)

And as result the buffer "**file_1.txt**" and "**file_2.txt**" was swapped. 

![step_5](https://user-images.githubusercontent.com/303539/44298948-78ab9c80-a2f5-11e8-88b4-ac1871cf857c.png)

But I think it's very slow.

Is it possible when I stay on buffer "**file_1.txt**" and press, e.g. `<M-S-right>` to swap buffer "**file_1.txt**" and "**file_2.txt**".

Or when I stay on buffer "**file_2.txt**" and press, e.g. `<M-S-down>` to swap buffer "**file_2.txt**" and "**file_4.txt**".

I think it will be very fast and convenient.

**Comment by abo-abo** [comment]
> I think it will be very fast and convenient.

Maybe so, but it's not the responsibility of `ace-window`. This looks like a feature request for `windmove`.

**Comment by articuluxe** [comment]
This is already available in repo github.com/emacsmirror/buffer-move.git

**Comment by lmdic** [comment]
Windows 10, Emacs 25.1

After install from Melpa and set in my init.el

(require 'buffer-move)

I restart Emacs and get error:

Symbol's value as variable is void: closed

When I evaluate

`(require 'buffer-move)`

I get error:

```
Debugger entered--Lisp error: (void-variable closed)
eval-buffer(#<buffer load> nil "mypath_to_emacs/emacs/.emacs.d/elpa/buffer-move-20160615.1103/buffer-move.el" nil t) ; Reading at buffer position 7
load-with-code-conversion("mypath_to_emacs/emacs/.emacs.d/elpa/buffer-move-20160615.1103/buffer-move.el" "mypath_to_emacs/emacs/.emacs.d/elpa/buffer-move-20160615.1103/buffer-move.el" nil t)
require(buffer-move)
eval((require (quote buffer-move)) nil)
elisp--eval-last-sexp(nil)
eval-last-sexp(nil)
funcall-interactively(eval-last-sexp nil)
call-interactively(eval-last-sexp nil nil)
command-execute(eval-last-sexp)
```
