### ISSUE TITLE
Missing window selection when there are three windows and one is ignored

### ISSUE THREAD

**Issue by Alexander-Miller** [abo-abo/ace-window#144]
See https://github.com/Alexander-Miller/treemacs/issues/301

**Comment by abo-abo** [comment]
This is expected behavior. For the purposes of `ace-window` there are only 2 selectable windows. Set `aw-dispatch-always` if you don't like this behavior.

**Comment by Alexander-Miller** [comment]
> there are only 2 selectable windows

And focus is on the third one which is set to be ignored. That means that out of the 3 visible windows 2 are valid targets for ace-window, so foregoing dispatch is not correct in this case. It would only be right if one of the not-ignored windows was focused.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by Alexander-Miller** [comment]
Fix is confirmed :+1:
