### ISSUE TITLE
Not show numbers when I switch between 2 frames.

### ISSUE THREAD

**Issue by lmdic** [abo-abo/ace-window#145]
Emacs 26.1, Windows 10, I install package (require 'ace-window)

If I has only one frame it's work fine.
Here result:

![swipe1](https://user-images.githubusercontent.com/303539/48895072-e7484b00-ee4c-11e8-93c9-f988bbba6caa.png)

As you can see it show numbers (2, 3). Nice.
But if I create second frame and switch between frames, sometimes it's not show all numbers. 
Here example:

![swipe2](https://user-images.githubusercontent.com/303539/48895243-4efe9600-ee4d-11e8-98c9-82b20ff85b20.png)

As you can see it not show number **3**

**Comment by abo-abo** [comment]
Can't reproduce on Emacs 26.1 / Linux. I made 2 frames, with 2 windows in each. All windows get a character displayed.

**Comment by lmdic** [comment]
> Can't reproduce on Emacs 26.1 / Linux. I made 2 frames, with 2 windows in each. All windows get a character displayed.

Try it a few times. It does not always happen immediately.

**Comment by abo-abo** [comment]
What's the `major-mode` of the window that doesn't get a character? Is it typically windows of this `major-mode` that don't get a number?

**Comment by lmdic** [comment]
In buffer than not show number I start shell (`M-x shell`)

**Comment by lmdic** [comment]
> Tried with a shell buffer, still can't reproduce.

I found problem. Start some process in shell mode that generate many text. E.g. logs.
And then input command `ace-window`. Then number not show in buffer that show shell.

**Comment by axelson** [comment]
I've seen this even without scrolling output when `aw-leading-char-face` is given a larger height than the rest of the buffer

**Comment by abo-abo** [comment]
> I've seen this even without scrolling output when aw-leading-char-face is given a larger height than the rest of the buffer

Thanks for the comment. This was indeed the key to reproduce the issue.

Please test.

**Comment by axelson** [comment]
Thanks! I'll give it a try.
