### ISSUE TITLE
Does not work with helm in minibuffer

### ISSUE THREAD

**Issue by To1ne** [abo-abo/ace-window#15]
How to reproduce:
- Activate helm
- Open at least 2 windows (<kbd>C-x 2</kbd>)
- Do some helm command (e.g. `helm-M-x`)
- Do `ace-window` (e.g. <kdb>M-p</kbd> when bound to that)
- helm-M-x will eat all key presses, and the ace-window indicators will remain

I am not sure if this is an ace-windows bug, and if it can be fixed. I only would report and ask if this can be fixed.

**Comment by glucas** [comment]
Awesome, I just came to report my issues with ace-window + helm and it is already fixed. Plans for when it will be released?

**Comment by abo-abo** [comment]
@glucas, you mean tagged? I tagged it just now, although MELPA Stable
isn't in a great place right now, since it's not being used by its own
maintainers. But it doesn't cost me anything to push a tag.
