### ISSUE TITLE
Ignoring childframes 

### ISSUE THREAD

**Issue by Yevgnen** [abo-abo/ace-window#150]
Hi, now more and more package use childframe to display thing like `eldoc` or other informations. Accidentally I use `ace-window` when a childframe is being displayed and numbered by `ace-window`. Can childframes like this can be ignore by `ace-window`? Thanks.

**Comment by abo-abo** [comment]
Thanks.

**Comment by butala** [comment]
The code merged to close this issue breaks my emacs. I use emacs prelude (https://github.com/bbatsov/prelude) which sets
```
(global-set-key [remap other-window] 'ace-window)
```
But, now when I do `C-x o` I get the error
```
aw-ignored-p: Symbol’s function definition is void: frame-parent
```
It seems my emacs does not grok `frame-parent`. Is there some action I can take to fix this issue? Does this merge assume something that is different about my emacs?

**Comment by butala** [comment]
It seems this issue has been address in GH-151.

**Comment by Eeemil** [comment]
The `Symbol’s function definition is void: frame-parent.` is affecting me too on `GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian` with ace window `ace-window-20181220.1446` whenever `ace-window` is called.

[GH-151](https://github.com/abo-abo/ace-window/pull/151) fixes the issue though.
