### ISSUE TITLE
no parent-frame in emacs 25

### ISSUE THREAD

**Issue by lcacciari** [abo-abo/ace-window#152]
Today update broke under emacs  25.2.2, that being the default version installed on ubuntu machines.

Emacs complain about function value of symbol 'frame-parent' being void which isn't surprising as 
this function has been introduced in version 26.0 

in fact, in the 25.2.2 version of the manual there is no section named 'Child Frames' in the 'Frames' chapter of the ELisp manual.

**Comment by Khady** [comment]
Debian only has 25.1.1, so is impacted too.

**Comment by 3452f435** [comment]
It wasn't working for me either in Emacs 27. Changed parent-frame to frame-parent and it does now.

**Comment by chenl** [comment]
Reverting 2e3b9562b52e3ce2def3adf32f5ec8fe77f573d6 worked for me.

**Comment by bymoz089** [comment]
same here, with emacs 25.

**Comment by bgschaid** [comment]
Fixed this temporarily with replacing the offending line with
````      
      ;; ignore child frames
      (and
       (fboundp 'frame-parent)
       (frame-parent (window-frame window)))
      ;; Ignore selected window if `aw-ignore-current' is non-nil.
````

**Comment by abo-abo** [comment]
Thanks for reporting. This was fixed a few days ago, I believe. Please test.

**Comment by abo-abo** [comment]
Thanks, closing.
