### ISSUE TITLE
Documentation: Add make-frame-visible to after-make-frame-functions

### ISSUE THREAD

**Issue by chckyn** [abo-abo/ace-window#153]
There is a bug with `ace-window-display-mode` where newly created frames that are not yet considered visible by `frame-visible-p` (when evaluated in `ace-window-list`) do not get updated correctly by `aw-update`. This problem is likely window manager specific, so it may not be possible to fix inside of ace-window.

To solve this problem for my window manager, I added the following line to my `init.el`:

  `(add-hook 'after-make-frame-functions (lambda (f) (make-frame-visible f)))`

This should ensures that newly created frames are considered visible by ace-window. I'm not aware of any use cases where a new frame should not be considered visible, so maybe this is a bug in Emacs.

I suggest this problem be noted in the documentation with the fix I used for my setup.

**Comment by abo-abo** [comment]
Thanks, `make-frame-visible` is now the default.
