### ISSUE TITLE
Question: dimmer.el alongside ace-window

### ISSUE THREAD

**Issue by azzamsa** [abo-abo/ace-window#155]
Hi abo-abo.

I am dimmer.el user, I can prevent dimmer to dim certain windows using:

```elisp
(setq dimmer-exclusion-predicates '(helm--alive-p window-minibuffer-p))
  (setq dimmer-exclusion-regexp-list
        '("^\\*[h|H]elm.*\\*" "^\\*Minibuf-[0-9]+\\*"
          "^.\\*which-key\\*$" "^*Messages*" "*LV*"))
  
```

When I use ace-window. All other unfocused buffer already dimmed by dimmer.el, so when I invoke ace-window, the hint that ace-window put in the top left of windows are dimmed too.

Do you have any idea for this ?

**Comment by abo-abo** [comment]
Maybe you can customize `aw-leading-char-face` to your liking? For instance, make it bigger, or add a custom `:background`?:

```elisp
(set-face-background 'aw-leading-char-face "blue")
```

**Comment by azzamsa** [comment]
Yes, I am aware of those, I've read https://oremacs.com/2015/02/27/ace-window-leading-char/ before.

I opened this issue, I think maybe there will be a workaround from ace-window side, so it could ignore any face value from other package in those buffers.

But I'm okay with my current configuration now, I make the leading-char higher then add box around them. It bit better now :)

``` elisp
(use-package ace-window
  :bind ("s-b" . ace-window)
  :config
  (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l))
  (global-set-key [remap other-window] 'ace-window)
  (setq aw-background nil)
  :custom-face
  (aw-leading-char-face
        ((t
          (:box
           (:line-width 3 :color "lemon chiffon" :style released-button)
           :height 2.0)))))
```

Thank you for ace-window.
