### ISSUE TITLE
Commit 88e48db56a176363121058b15b965324dc8e92c9 introduced regression

### ISSUE THREAD

**Issue by vp1981** [abo-abo/ace-window#157]
Hello,
after commit 88e48db56a176363121058b15b965324dc8e92c9 I faced with strange behaviour of 'ace-window'.

If I has only two windows I could switch between them using shortcut, but if I split any of window in either direction then after the call to `ace-window` (shortcut key is bound to this function) I see in minibuffer:
```
unexpected: 140
```
In `*Messages*` buffer I see
```
aw--face-rel-height: unexpected: 140
```

I didn't try to revert that commit and test without it because I know that previous commit, 1b1950e15ce51ff8ff2c7f842d4b51f868826a00 works fine.

I know very little about Emacs Lisp and don't understand why that branch is triggered. May be to use `numberp` instead of `floatp`? The `140` seems to be an integer not a float.

**Comment by abo-abo** [comment]
Thanks, I think it should be fixed now, but please test. Could you find what exactly in your config produces the number `140`? I suspect it's some theme's character height, i.e. it's 140% of the default height. But all themes I've seen set the height using floats, e.g. `1.4`.

**Comment by vp1981** [comment]
Hello,
I'm answering just to clarify the situation.

I don't remember how but I set the `:height` of `aw-leading-char-face` to `140` (I could set it by "Customize" or by hand) but all was working fine till now. Meanwhile other values in `custom-set-faces` for `:height` are floats so I changed the `140` to `1.4`. After this change 'ace-window' works as usual.
