### ISSUE TITLE
Reopen: Window numbers or characters are missing sometimes

### ISSUE THREAD

**Issue by rswgnu** [abo-abo/ace-window#165]
I am using: Package-Version: 20190210.1648 under a fairly recent Emacs 26 build and I still see this problem whenever the buffer in a window is horizontally scrolled so that the left-most characters are not visible. ace-window should account for (window-hscroll) and place the leading-char within a visible part of the window.  I am using a leading character with a large 3.0 height.

Ace-window also misses a number of other boundary conditions that this fixes.

Here's a patch that I tested with 81 windows and it displayed the leading-char properly in all of them except buffers receiving output during the aw--lead-overlay function call since the output may scroll the overlay point outside the window's visible range, e.g. the _Messages_ buffer. Prior to this patch maybe 10% of the windows failed to display the overlay character; now it is closer to 1%.

[aw-diff.txt](https://github.com/abo-abo/ace-window/files/2876469/aw-diff.txt)

I hope you can use it or adapt it for use.  Thanks for ace-window; it is one of the handiest packages out there.

**Comment by abo-abo** [comment]
Thanks.

**Comment by rswgnu** [comment]
> On Feb 19, 2019, at 4:48 AM, Oleh Krehel <notifications@github.com> wrote:
> 
> Closed #165 via a429c66.
> 

Great.

Cheers,

Bob

**Comment by mrkkrp** [comment]
Now every time I use `avy-window` it scrolls my window. I think this happens because I set `scroll-margin` to `3` (try for yourself). Some recent change (I suspect this one) screwed it.

**Comment by mrkkrp** [comment]
Is my comment being ignored? It is an actual issue for me, and it's clearly a regression.

**Comment by rswgnu** [comment]
The idea of the recent patch is to scroll a buffer only when needed to display the window selection id in the window.  If you are sure that scrolling is occurring when not needed to achieve this, then provide basic code that generates the window config that reflects the problem, the steps to recreate it and then I can look at resolving it.  Oleh of course would have the final say.

-- Bob

**Comment by abo-abo** [comment]
@mrkkrp I think the scrolling issue is fixed now, please confirm. Sorry for ignoring the thread, I currently have a very large backlog.
