### ISSUE TITLE
Invocations of ace-window scroll current window

### ISSUE THREAD

**Issue by mrkkrp** [abo-abo/ace-window#166]
This is the bug introduced by solution to #165.

Instructions how to reproduce it:

1. Run Emacs like this `emacs -Q` to avoid loading personalized configuration.
2. Evaluate `(package-initialize)`.
3. Evaluate `(require 'ace-window)`.
4. Open a file which is long enough not to fit in a window all at once.
5. Split window vertically, then horizontally. This is just so we can have the actual markers when we run `ace-window`.
6. Evaluate `(setq scroll-margin 3)` setting scroll margin.
7. Now run `ace-window`.
8. Observe how the current window is scrolled. You can hit `Ctrl-g` now cancelling actual jump.
9. Repeat 7-8 till it's obvious enough that something is really wrong.

cc @rswgnu

**Comment by mrkkrp** [comment]
That fix was really unfortunate, I'd be OK with just reverting that. The bug is very very very annoying.

**Comment by rswgnu** [comment]
It is just a matter of the code not yet accounting for a scroll-margin of non-zero.
Pull request #167 should fix it.

**Comment by mrkkrp** [comment]
I suffer every day.

**Comment by mrkkrp** [comment]
@rswgnu @abo-abo So you asked for a way to reproduce the problem and I provided that, can we move forward with this?

**Comment by rswgnu** [comment]
Did you try my patch and did it resolve your issues?

**Comment by mrkkrp** [comment]
I wasn't aware of your patch because GitHub did not notify me about it. I'm going to try it shortly.
