### ISSUE TITLE
ace-jump-mode 2.0 compat

### ISSUE THREAD

**Issue by fleimgruber** [abo-abo/ace-window#17]
Emacs 24.4.1
ace-jump-mode 2.0 (melpa-stable)
ace-window (latest from melpa)

On `ace-window`, I get
```
aw-list-visual-area: Symbol's function definition is void: ace-jump-list-visual-area
```

I am loading `ace-jump-mode` and `ace-window` via `use-package`. It seems that `ace-jump-list-visual-area` is not exposed by `ace-jump-mode` (anymore?). I tried manually requiring `ace-jump-mode`, no change.

**Comment by abo-abo** [comment]
Something weird is happening on your end: `ace-jump-mode` is 7 months
old in both MELPA Stable and MELPA. And this is the first time this issue happens.

I just uninstalled `ace-jump-mode` from MELPA and installed from MELPA
Stable: `ace-jump-list-visual-area` is still here.
Maybe delete both packages, restart Emacs and re-install.

**Comment by fleimgruber** [comment]
Hm, after some install, remove and reinstall cycles it works now with both packages in their stable versions.

Sorry for the noise.

**Comment by abo-abo** [comment]
No problem. Glad it worked out.
