### ISSUE TITLE
changing windows programatically (in a function) not interactively

### ISSUE THREAD

**Issue by TRSx80** [abo-abo/ace-window#170]
I have been trying to do as stated in the title, but cannot seem to figure out a way by using either ace-window or ace-select-window?

I want to do something like (ace-select-window 2) but that returns (wrong-number-of-arguments (0 . 0) 1). I have tried a bunch of variations, and also tried to read the code but sadly I am only a fledgling lisp wizard, and "this foe is beyond me."

**Comment by abo-abo** [comment]
Here you go:

```elisp
(defun my-test ()
  (interactive)
  (let ((wnd (aw-select "Test")))
    (message "You selected: %S" wnd)))
```

**Comment by TRSx80** [comment]
I'm sorry abo-abo, I have tried playing with it a bunch, but still cannot seem to figure it out. :(

If I define the function my-test and then try to execute something like (my-test 2) I am still getting wrong number of arguments.

If I try and put the number 2 instead of Test eg. `(aw-select "2")` and then execute (my-test) that doesn't work either.

I'm sorry but I can't seem to follow your code. :(

**Comment by abo-abo** [comment]
You can use <kbd>M-x</kbd> `ielm` to play around with this. `(aw-select "Test")` returns a window object, which you can later pass to `select-window`.

If you need more help with Elisp, read: https://www.gnu.org/software/emacs/manual/html_node/eintr/index.html.

**Comment by jcs090218** [comment]
I just wrote this function, hope this would help!

```el
(defun jcs-ace-select-window (win-id)
  "Use `ace-window' to select the window by using window index.
WIN-ID : Window index."
  (let ((wnd (nth win-id (aw-window-list))))
    (when wnd
      (select-window wnd)
      (select-frame-set-input-focus (selected-frame)))))
```

You can call it this way.
```el
(jcs-ace-select-window 0)
```

**Comment by abo-abo** [comment]
OK, I see what you were going for. Closing the issue.
