### ISSUE TITLE
Feature request: Option to disable the leading char overlay

### ISSUE THREAD

**Issue by valff** [abo-abo/ace-window#173]
I'm using `ace-window-display-mode` to display the leading char at the mode line. And I want to disable the leading char overlay completely.

As a workaround I'm using this hack:

```elisp
(advice-add 'aw--lead-overlay :override (lambda (&rest _)))
```

It would be great to introduce an option similar to `aw-background`, but for the char overlay.

**Comment by abo-abo** [comment]
Thanks.

**Comment by valff** [comment]
Thank you! Awesome package.
