### ISSUE TITLE
Window number overlays are missing unless ace-window-display-mode is enabled

### ISSUE THREAD

**Issue by drgillis** [abo-abo/ace-window#174]
The window number overlay fails to show up unless `ace-window-display-mode` is enabled and `aw-display-mode-overlay` is non-nil, which means that if `ace-window-display-mode` is disabled, there is no way to have the overlay appear. This seems to be a direct consequence from the addition of the conditional in the following lines in the most recent commit ([in ace-window.el in the `aw-select` function, lines 552-555](https://github.com/abo-abo/ace-window/blob/196382b5c85f110873156463fc387e39334a9880/ace-window.el#L552)):

```
(if (and ace-window-display-mode
         aw-display-mode-overlay)
    #'aw--lead-overlay
  (lambda (_path _leaf)))
```

**Comment by abo-abo** [comment]
Thanks, fixed. Sorry for introducing this silly bug.
