### ISSUE TITLE
Ace window doesn't display window number in overlay when the first line in the window is a blank line

### ISSUE THREAD

**Issue by quanticle** [abo-abo/ace-window#175]
If the buffer scrolls past the end of the window, and the first line in the window is a blank line, the window number doesn't show if ace-window overlay is enabled.

To reproduce:
1. Create a file (e.g. `test.txt`)
2. Add a bunch of blank lines (e.g. `C-u 500 RET`)
3. `C-x 3` to split the window vertically
4. `C-x 2` to create a horizontal split
5. Scroll down a page or two with `C-v`
6. `M-o` (or whatever your ace-window key is)
7. Note that the window numbers don't show any more in the overlay

**Comment by quanticle** [comment]
After further investigation, it doesn't look like the overlay has anything to do with the problem, since it occurs even when I have `(setq aw-background nil)`.

**Comment by pkryger** [comment]
@quanticle I submitted #176 for slightly different scenario leading to missing overlay number. Perhaps this one is caused in similar circumstances?

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by quanticle** [comment]
Sorry it took me so long to respond! I didn't see that the issue was closed. I retested with an updated ace-window and can verify that the problem is fixed.

Thanks for taking care of this!

**Comment by abo-abo** [comment]
Thanks for the follow up.
