### ISSUE TITLE
Enhance user control over aw-keys display?

### ISSUE THREAD

**Issue by rubic** [abo-abo/ace-window#177]
Would it be possible to provide more user control over how the ace-window keys are displayed?  Here's an example of how the ```a``` key is displayed in my window:

![ace-window-marker](https://user-images.githubusercontent.com/198470/58431302-bc94b480-8072-11e9-9408-0a9ced82c072.png)

**Comment by abo-abo** [comment]
You can customize `aw-leading-char-face`. See `customize-group` `ace-window`.

**Comment by rubic** [comment]
This is what I was looking for: [Customizing ace-window leading char](https://oremacs.com/2015/02/27/ace-window-leading-char/). Thanks.
