### ISSUE TITLE
ace-window not working properly when using M-x calc

### ISSUE THREAD

**Issue by Grobwiefein** [abo-abo/ace-window#18]
Since commit fa7cb4d04467b8bd651f8e54b0b8c9febf54d8ad ace-window does not work properly when `M-x calc` is open. Using `C-x o` (which is bound to `ace-window` in my setup) does not allow jumping to windows with shortcuts but rather behaves like `other-window`. The problem only exists if no other windows/frames except those three are displayed. In other cases ace-window works as expected.

Prior to that commit, ace-window ignored the `*Calc trail*` window, i.e. when only calc and one other window were open the window switch was just between the calculator stack and the other window. When more than one non-calc window was open, ace-window showed the famous shortcuts within each window.

**Comment by abo-abo** [comment]
Thanks for reporting. Let me know if I broke anything else.

**Comment by Grobwiefein** [comment]
Awesome! Work’s like a charm again.
