### ISSUE TITLE
How to switch to minibuffer?

### ISSUE THREAD

**Issue by codesuki** [abo-abo/ace-window#183]
Sometimes I end up with the minibuffer active but focus on a file visiting buffer. Now I have to `C-x o` several times. Is there a way for jumping there with `ace-window` ? 

There was this issue which hinted that there was this functionality but in my case I only get choices for normal buffers. 
https://github.com/abo-abo/ace-window/issues/99

**Comment by abo-abo** [comment]
You can already select the minibuffer by simply calling `ace-window`. Please check with `make plain` from this repo and pressing <kbd>M-o</kbd>.

**Comment by codesuki** [comment]
I don't know what happened. I tried this yesterday and I didn't get a number in the minibuffer. Today I try it and it works 🤣 
I might have been overworked.
Thanks! Works perfectly.

**Comment by codesuki** [comment]
BTW your packages are awesome!

**Comment by abo-abo** [comment]
Thanks!
