### ISSUE TITLE
ace-window vs other-window: changing frames

### ISSUE THREAD

**Issue by pennersr** [abo-abo/ace-window#184]
`ace-window` is documented as:

> "By default, behaves like extended `other-window'."

Suppose I have two frames open.  The normal `other-window` behavior is that C-x o sticks to switching windows within the active frame. However, `ace-window` does not behave like that, and activates a window in another frame.  

Is that intentional? Is there a way of preventing that? Ideally I would like to bind `ace-window` to C-x o but due to this difference in behavior I cannot.

**Comment by abo-abo** [comment]
You can configure:

```elisp
(setq aw-scope 'frame)
```

**Comment by pennersr** [comment]
Thanks! Perhaps it is an idea to alter the documentation to clarify this.

> "By default, behaves like `other window`, with the exception that depending on the value of `aw-scope`  it switches to other windows within other frames as well.

**Comment by abo-abo** [comment]
Thanks.
