### ISSUE TITLE
Split vertically really splitting horizontally and vice versa.

### ISSUE THREAD

**Issue by donileo** [abo-abo/ace-window#186]
For some odd reason without having modified the default functions, when I call `ace-window b` the window splits vertically for me instead of horizontally. Calling to split vertically via the `ace-window v` actually ends up splitting horizontally. I am using the latest contents from melpa for ace-window.

Telling emacs to split via `M-x split-window-right RET` and `M-x split-window-below RET` splits the windows correctly.

Doing a `M-x describe-var RET aw-dispatch-alist` prints out:

```
((120 aw-delete-window "Delete Window")
 (109 aw-swap-window "Swap Windows")
 (77 aw-move-window "Move Window")
 (99 aw-copy-window "Copy Window")
 (106 aw-switch-buffer-in-window "Select Buffer")
 (110 aw-flip-window)
 (117 aw-switch-buffer-other-window "Switch Buffer Other Window")
 (101 aw-execute-command-other-window "Execute Command Other Window")
 (70 aw-split-window-fair "Split Fair Window")
 (118 aw-split-window-vert "Split Vert Window")
 (98 aw-split-window-horz "Split Horz Window")
 (111 delete-other-windows "Delete Other Windows")
 (84 aw-transpose-frame "Transpose Frame")
 (63 aw-show-dispatch-help))
```

Which looks correct..

**Comment by abo-abo** [comment]
"v" does what `split-window-vertically` does. It's just a matter of terminology of the built-in Emacs function. So I think we can close this.
