### ISSUE TITLE
Some keys do not work in `aw-keys`

### ISSUE THREAD

**Issue by b3n** [abo-abo/ace-window#190]
This works fine:
`(setq aw-keys '(?\C-m ?, ?. ?n ?e ?i ?l ?u ?y))`

But this causes problems:
`(setq aw-keys '(?\s-m ?, ?. ?n ?e ?i ?l ?u ?y))`

It results in the error "Unknown key 8388717" when running `ace-window`.

My intention is to use Super-m rather than Ctrl-m.

**Comment by abo-abo** [comment]
The issue here is that `avy--key-to-char` doesn't know how to map `?s-m` to a char.

Here's how to fix it:

```elisp
(add-to-list 'avy-key-to-char-alist '(?\s-m . ?🧐))
```

**Comment by b3n** [comment]
That works perfectly, thank you!
