### ISSUE TITLE
Why not copy point and window-start in aw-copy-window?

### ISSUE THREAD

**Issue by ramblehead** [abo-abo/ace-window#193]
I am using ace-window quite often - both in my elisp extensions and in normal workflow.

I think, it might be more convenient if ```aw-copy-window()``` copies window and point position as well as the buffer:

```elisp
(defun aw-copy-window (window)
  "Copy the current buffer to WINDOW - including window-start and point."
  (let ((buffer (current-buffer))
        (window-start (window-start))
        (point (point)))
    (aw-switch-to-window window)
    (switch-to-buffer buffer)
    (set-window-start (frame-selected-window) window-start)
    (goto-char point)))
```

Are there workflows/libs where such additional logic could be harmful?

**Comment by abo-abo** [comment]
Sounds like a nice improvement. Please PR.
