### ISSUE TITLE
Highlight two characters for 2 character jumps

### ISSUE THREAD

**Issue by hura** [abo-abo/ace-window#21]
VIM's Easymotion does this:

![GIF](https://camo.githubusercontent.com/d5f800b9602faaeccc2738c302776a8a11797a0e/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f333739373036322f323033393335392f61386539333864362d383939662d313165332d383738392d3630303235656138333635362e676966)

In case the gif is down in the future:

https://github.com/Lokaltog/vim-easymotion

(They also have a few other interesting commands. Personally I'd find it useful to copy a line from another line and paste it at the current cursor position without actually having to go there.)

**Comment by abo-abo** [comment]
The different faces can be added easily, but I don't like them.
I can add some customization for that if you really want.

**Comment by hura** [comment]
No I also don't like the different faces. It makes no sense. Not sure since when they have those. My VIM Easymotion version still just has one face and different intensity for 1st/2nd character.
Haven't tested your code yet but will soon.

Thanks for the awesome work! You might have to rename your plugin soon, now that it does much more :)

**Comment by abo-abo** [comment]
> You might have to rename your plugin soon, now that it does much more

That's the plan, I just have to find a clear separation line between
`ace-window`, `avy` and `avy-jump`.
