### ISSUE TITLE
Add a option for show ace-window dispatch actions help immediately after invoke ace-window.

### ISSUE THREAD

**Issue by zw963** [abo-abo/ace-window#211]
Basically, after i invoke `ace-window`, i expect i can show following help immediately.(type ? automatially)

![image](https://user-images.githubusercontent.com/549126/116774790-88fa0a80-aa91-11eb-8ded-3cd4015c7330.png)

Sure, i think a better way is to use hydra, like this.

![image](https://user-images.githubusercontent.com/549126/116774840-db3b2b80-aa91-11eb-9857-f4c57d8bfae4.png)

**Comment by audiophfil** [comment]
I was able to get this to work by queuing the "?" key command prior to calling `ace-window`:

```
(progn
	   (setq unread-command-events (listify-key-sequence (kbd "?"))) ;; Queue "?" key command to be sent
	   (ace-window nil))

```

**Comment by zw963** [comment]
> I was able to get this to work by queuing the "?" key command prior to calling `ace-window`:
> 
> ```
> (progn
> 	   (setq unread-command-events (listify-key-sequence (kbd "?"))) ;; Queue "?" key command to be sent
> 	   (ace-window nil))
> ```

It works, thank you! following is my config:

```cl
(global-set-key [remap other-window] (lambda ()
                                       (interactive)
                                       (progn
                                         (setq unread-command-events (listify-key-sequence (kbd "?"))) ;; Queue "?" key command to be sent
                                         (ace-window nil))
                                       ))
```
