### ISSUE TITLE
error: avi--overlay-post: Wrong type argument: listp, 97

### ISSUE THREAD

**Issue by zeltak** [abo-abo/ace-window#22]
GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.7)
 of 2015-01-17 on bisson

to produce: issue any avi-command such as 
avi-goto-line

and the error appears. 

im not very technical but would be happy to provide more info and test this if instructed how to

best

Z

**Comment by abo-abo** [comment]
What's the MELPA version of `ace-window` that you have installed?
Did you try to reinstall and restart Emacs?

**Comment by zeltak** [comment]
version is 0150303.1449
uninstalling ace-window and re installing seems to have done the trick

thx!

Z
