### ISSUE TITLE
Can't use some functions, like find-file, with "e" execute command other window 

### ISSUE THREAD

**Issue by josephmturner** [abo-abo/ace-window#220]
Thank you for `ace-window`!

When I press "C-x ace-window 1 C-x p p", I expect to be prompted to choose a file.
Instead, I get the error `aw-execute-command-other-window: Wrong number of arguments: (1 . 2), 0`

I'm using emacs 27.2, with a blank `init.el`, just importing `ace-window`.

Please let me know if I'm doing something wrong.

**Comment by josephmturner** [comment]
I realize now that my prior bug report was flawed. The command that is not working as expected is `M-o e 1 C-x p p`, which should run the command `project-switch-project` in the selected window.

Instead, I get the following error: `aw-execute-command-other-window: Wrong number of arguments: (1 . 1), 0`

**Comment by BonfaceKilz** [comment]
@josephmturner the above PR fixes this issue.  In the mean time while this is being reviewed, you could just override the offending function in your emacs conf file as such:

```
(defun aw-execute-command-other-window (window)
  "Execute a command in WINDOW."
  (aw-switch-to-window window)
  (unwind-protect
      (call-interactively
       (key-binding
        (read-key-sequence
         "Enter key sequence: ")))
    (aw-flip-window)))
```

**Comment by josephmturner** [comment]
@BonfaceKilz Great! This does fix the issue! Thank you!

**Comment by josephmturner** [comment]
Makes sense that you'd use `call-interactively` there.
