### ISSUE TITLE
Get inherited faces in posframe

### ISSUE THREAD

**Issue by seagle0128** [abo-abo/ace-window#227]
Hi @abo-abo ,
I think the we should use the inherited colors in posframe, e.g.

```elisp
(face-foreground 'aw-leading-char-face nil t)
(face-background 'aw-leading-char-face nil t)
```

And I suggest to add new faces for child frame.

https://github.com/abo-abo/ace-window/blob/0d9a89edafca53a09946e3a59ed64a0b975a0b8a/ace-window-posframe.el#L26-L27

**Comment by abo-abo** [comment]
Sounds good. Please PR
