### ISSUE TITLE
Is necessary to show ace window key on mode-line?

### ISSUE THREAD

**Issue by deftsp** [abo-abo/ace-window#24]
Personally, I like to show the ace window key as the first char on mode-line to quick switch.

Maybe it have some conflict with the design goal o ace-window. Howerver I have patched it to enabe that.  If necessary, I'll give my pull request.

**Comment by abo-abo** [comment]
Alright, let's see it.

**Comment by abo-abo** [comment]
Merged with some adjustments, thanks.
