### ISSUE TITLE
Ace Window Key on Mode Line accumulates when theme changes

### ISSUE THREAD

**Issue by zenshinji** [abo-abo/ace-window#27]
When I switch between solarized-light and solarized-dark either manually or via the theme-changer package the Ace Window Key is duplicated. The same thing happens when I manually change the smart-mode-line theme between light and dark.

For example, if a window is flagged with 'a' as expected when 'ace-window-display-mode' is enabled, after changing the theme 'aa' is displayed. Changing the theme again displays 'aaa'. The functionality remains constant, simply the displayed character accumulates. Toggling 'ace-window-display-mode' twice resets the displayed value as expected.

GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8) of 2015-03-03 on lm-lvm-tpt430
Ace-Window 20150308.1339
Smart-Mode-Line 20150312.1736
Solarized-Theme 20150308.128
Theme-Changer 20130725.1919

Let me know if I can provide more information.

**Comment by abo-abo** [comment]
See if this works.

**Comment by zenshinji** [comment]
Hmmm. I'm getting "aw-window-list: Symbol's function definition is void: global".

**Comment by abo-abo** [comment]
It works fine for me. Can you give me a recipe with a small amount of steps to reproduce the issue?

**Comment by zenshinji** [comment]
Looks like a bad update on my side. Deleted and installed. Now it's working great. Thanks!
