### ISSUE TITLE
window-number lighter should inherit mode-line-faces

### ISSUE THREAD

**Issue by nsemrau** [abo-abo/ace-window#28]
The mode-line lighter's colour is black by default. This makes the numbers illegible in themes with a dark mode-line (i.e. zenburn, tango-dark).

In swiper (excellent package, btw), Steve Purcell committed a patch to inherit standard faces for the highlighting (https://github.com/abo-abo/swiper/commit/835208a0ec80e5e8d8109b6c96406002c9642401). Please use this inheritance approach for the numbering lighter, too.

**Comment by abo-abo** [comment]
Alright, which face do you suggest to inherit?

**Comment by abo-abo** [comment]
This face looks reasonable, I think.
