### ISSUE TITLE
FR: Customize key sequences instead of keys

### ISSUE THREAD

**Issue by jhonnyseven** [abo-abo/ace-window#30]
Instead of giving list of keys give a list of key sequences which avy
should use as the targets.

What I would like is to have targets which recognize left and right
hand keys and avoid giving targets where two keys come from the same
hand.

So _my_ optimal order of targets would be something like this:
1. Single letters
2. Alternating hand 2-letter sequences
3. Alternating hand 3-letter sequences
4. Same hand 2-letter sequences
5. Same hand 3-letter sequences
And so on...

**Comment by abo-abo** [comment]
The standard `aw-keys` is 9 chars long. That means you need at least 9 windows for `avy-tree` to
kick in. I don't expect this to occur too often.

So 95% of the time you're getting this (note the ordering):

```el
aw-keys
;; =>
;; (97 115 100 102 103 104 106 107 108)

(avy-tree (make-list 8 0) aw-keys)
;; =>
;; ((97 leaf . 0)
;;  (115 leaf . 0)
;;  (100 leaf . 0)
;;  (102 leaf . 0)
;;  (103 leaf . 0)
;;  (104 leaf . 0)
;;  (106 leaf . 0)
;;  (107 leaf . 0))
```

For a larger candidate pool you get this:

```el
(avy-tree (make-list 20 0) aw-keys)
;; =>
;; ((97 leaf . 0)
;;  (115 leaf . 0)
;;  (100 leaf . 0)
;;  (102 leaf . 0)
;;  (103 leaf . 0)
;;  (104 leaf . 0)
;;  (106 leaf . 0)
;;  (107 (97 leaf . 0)
;;       (115 leaf . 0)
;;       (100 leaf . 0)
;;       (102 leaf . 0))
;;  (108 (97 leaf . 0)
;;       (115 leaf . 0)
;;       (100 leaf . 0)
;;       (102 leaf . 0)
;;       (103 leaf . 0)
;;       (104 leaf . 0)
;;       (106 leaf . 0)
;;       (107 leaf . 0)
;;       (108 leaf . 0)))
```

If you get your left-hand/right-hand way, you're likely to lose the intuitive ordering.  You can
actually already get your ordering by rearranging `aw-keys`.  Notice that the last ones are the
first ones to be used as a branch node, so just order them left/right starting from end.

**Comment by jhonnyseven** [comment]
I was thinking about `avi-goto-line` , `avi-goto-word-0` and friends.

**Comment by jhonnyseven** [comment]
I thought this would be easy to implement as a single candidate list, but that doesn't work. E.g. `(a b ab ba aa bb)` doesn't make sense. You would have to remove the single letters to make the double letters to work.

**Comment by abo-abo** [comment]
I see. Try to make this tree in your way, while keeping the depth of 2 and 6 leafs:

```el
(avy-tree (make-list 30 0)
          '("a" "s" "g" "h" "j" "d" "k" "f" "l"))
;; =>
;; (("a" leaf . 0)
;;  ("s" leaf . 0)
;;  ("g" leaf . 0)
;;  ("h" leaf . 0)
;;  ("j" leaf . 0)
;;  ("d" leaf . 0)
;;  ("k" ("a" leaf . 0)
;;       ("s" leaf . 0)
;;       ("g" leaf . 0)
;;       ("h" leaf . 0)
;;       ("j" leaf . 0)
;;       ("d" leaf . 0))
;;  ("f" ("a" leaf . 0)
;;       ("s" leaf . 0)
;;       ("g" leaf . 0)
;;       ("h" leaf . 0)
;;       ("j" leaf . 0)
;;       ("d" leaf . 0)
;;       ("k" leaf . 0)
;;       ("f" leaf . 0)
;;       ("l" leaf . 0))
;;  ("l" ("a" leaf . 0)
;;       ("s" leaf . 0)
;;       ("g" leaf . 0)
;;       ("h" leaf . 0)
;;       ("j" leaf . 0)
;;       ("d" leaf . 0)
;;       ("k" leaf . 0)
;;       ("f" leaf . 0)
;;       ("l" leaf . 0)))
```

**Comment by jhonnyseven** [comment]
The candidate search would have to be completely changed to make this work. Keep the tree but add a terminal key to a sequence if that sequence is a prefix to some other candidate. And then you would retry on new input if last input wasn't in the tree.

I'll close this. Maybe I'll look if this easy implement later.
