### ISSUE TITLE
Args out of range: #<buffer *shell*>, 18, 19

### ISSUE THREAD

**Issue by svend** [abo-abo/ace-window#31]
My emacs desktop settings restore my *shell* buffer. Since these run dtach, the *shell* buffer starts out empty. Running ace-window with an empty *shell* buffer results in the following error:

```
Args out of range: #<buffer *shell*>, 18, 19
```

**Comment by abo-abo** [comment]
See if this helps.

**Comment by svend** [comment]
This fixed the issue for me. Thanks!

**Comment by abo-abo** [comment]
OK.
