### ISSUE TITLE
ace-window edits buffers

### ISSUE THREAD

**Issue by mrkkrp** [abo-abo/ace-window#32]
`ace-window` edits empty buffers inserting a space, if it's called when some window represents absolutely empty buffer. To reproduce this, split window until there is at least three windows. Now, open absolutely empty file in one of them, so you can't move the point to any position other then `(1,0)`. Call `ace-window`, in my case I can see that position of point has changed to `(1,1)` and asterisk `*` has appeared in status line indicating that the file has been edited. In my opinion switching between buffers should not edit them.

**Comment by abo-abo** [comment]
It's not possible to display an overlay in an empty buffer.
I think it's better to insert a space than to ignore a buffer.
An any case, empty buffers are very rare.

**Comment by mrkkrp** [comment]
I see. I think I should close the issue now, since it's rather about limitation of Emacs than bug of `ace-window`. Thanks for your explanation.
