### ISSUE TITLE
Respect case with avy-jump

### ISSUE THREAD

**Issue by tsdh** [abo-abo/ace-window#34]
I'd like to have an option to make the `avi-goto-*` functions respect case.  That is, when I type `E` I want to jump to a position with an uppercase E, not a lowercase e.

BTW, why is it called `avy-jump.el` with "y" but all functions start with the prefix `avi-`?  If the prefix and the file name/feature name are different, it makes things harder to discover.  At first, I required `avy-jump` and then wanted to check out its commands and options and was astonished that `C-h v avy-j<tab>` didn't show anything.  So I had to look into the file in order to figure out that it uses a prefix that's different from the file name and provided feature.

**Comment by abo-abo** [comment]
Alright, I'll do a big rename soon, probably tomorrow.

**Comment by tsdh** [comment]
That wasn't my intention, and I think you can't do that for backwards compatibility reasons.  I came to `avy-jump` because I've read a conversation on twitter about it (so it must be famous and with a super-large user-base!).  I know how to fix breakages but others might not.

I think this file/feature name/prefix mismatch has somehow become modern recently.  Ace-window does the same (oh, you again!) by prefixing its stuff with the abbreviation `aw-*`.  I guess that makes the poor user "Anton White" pretty angry because he prefixes his private vars and functions with `aw-*` for about 20 years now.

Well, but on the other hand: if you intend to integrate some of these packages into Emacs core at some point in time, at least then the prefixes will need to match the feature name, and in this case the sooner the renaming happens the better.

**Comment by tsdh** [comment]
While we are at it: `ace-window` would probably better be named `avy-window`.  But that would also mean renaming the ELPA package...

**Comment by abo-abo** [comment]
> That wasn't my intention, and I think you can't do that for
> backwards compatibility reasons.

I can just use `define-obsolete-function-alias` and remove the obsoletes 2-3 months later.

> Well, but on the other hand: if you intend to integrate some of
> these packages into Emacs core at some point in time, at least then
> the prefixes will need to match the feature name, and in this case
> the sooner the renaming happens the better.

Is this a strict rule? I've read somewhere that the prefix just needs to be unique, and it's even possible to use two prefixes within one package.

**Comment by tsdh** [comment]
Oleh Krehel <notifications@github.com> writes:

>> That wasn't my intention, and I think you can't do that for
>> backwards compatibility reasons.
>
> I can just use `define-obsolete-function-alias` and remove the
> obsoletes 2-3 months later.

Yes, and `define-obsolete-variable-alias'.

>> Well, but on the other hand: if you intend to integrate some of these
>> packages into Emacs core at some point in time, at least then the
>> prefixes will need to match the feature name, and in this case the
>> sooner the renaming happens the better.
>
> Is this a strict rule?

Well, it's not formulated as strict as I've thought.

,----[ (info "(elisp)Coding Conventions") ]
|    • You should choose a short word to distinguish your program from
|      other Lisp programs.  The names of all global symbols in your
|      program, that is the names of variables, constants, and functions,
|      should begin with that chosen prefix.  Separate the prefix from the
|      rest of the name with a hyphen, ‘-’.  This practice helps avoid
|      name conflicts, since all global variables in Emacs Lisp share the
|      same name space, and all functions share another name space(1).
|      Use two hyphens to separate prefix and name if the symbol is not
|      meant to be used by other packages.
| 
|      Occasionally, for a command name intended for users to use, it is
|      more convenient if some words come before the package’s name
|      prefix.  And constructs that define functions, variables, etc.,
|      work better if they start with ‘defun’ or ‘defvar’, so put the name
|      prefix later on in the name.
| 
|      This recommendation applies even to names for traditional Lisp
|      primitives that are not primitives in Emacs Lisp—such as
|      ‘copy-list’.  Believe it or not, there is more than one plausible
|      way to define ‘copy-list’.  Play it safe; append your name prefix
|      to produce a name like ‘foo-copy-list’ or ‘mylib-copy-list’
|      instead.
| 
|      If you write a function that you think ought to be added to Emacs
|      under a certain name, such as ‘twiddle-files’, don’t call it by
|      that name in your program.  Call it ‘mylib-twiddle-files’ in your
|      program, and send mail to ‘bug-gnu-emacs@gnu.org’ suggesting we add
|      it to Emacs.  If and when we do, we can change the name easily
|      enough.
| 
|      If one prefix is insufficient, your package can use two or three
|      alternative common prefixes, so long as they make sense.
`----

> I've read somewhere that the prefix just needs to be unique, and it's
> even possible to use two prefixes within one package.

So yes, it must be unique and you may use multiple prefixes if that
makes sense.  I don't have a clue when it makes sense.  Maybe its meant
that your package ace-window may use the prefixes ace-window, avy-jump,
and avy.  That makes sense because the package provides different
features which somehow belong together but can also be used separately,
and then its nice when each feature has its own prefix.

But I think having feature-name = prefix is at least a good rule of
thumb unless your feature is highlight-things-left-and-right-to-point in
which some abbreviation is almost inevitable.  As said, that helps
discovering new packages, and usually you can easily guess from
function/variable name to the package.

Aside from that, two-letter abbreviations as prefixes seem to be the
worst to me because those are almost certainly *not* unique because it
is common convention to prefix home-brewn functions/variables with your
initials.  There are probably dozens of emacs users whose initials are
AW, and probably one of them even has a variable `aw-keys' defined in
her ~/.emacs.

Bye,
Tassilo

**Comment by abo-abo** [comment]
> I'd like to have an option to make the avi-goto-* functions respect case

The commands use `case-fold-search`. Do you want `avy-case-fold-search`?

**Comment by tsdh** [comment]
Yes, I think that's what people would expect.  In the meantime, I added my own `th/avy-jump` command which dispatches between several `avy-goto-*` commands and also let-binds `c-f-s`.  But still I think such an option would be justified.
