### ISSUE TITLE
Some characters are ignored

### ISSUE THREAD

**Issue by manuel-uberti** [abo-abo/ace-window#36]
I think a screenshot explains this issue better than I coud.
![2015-05-05-110305_1280x800_scrot](https://cloud.githubusercontent.com/assets/8199224/7469578/b8e1cd1c-f315-11e4-9448-d47ed7c1c9ae.png)

I just grabbed latest ```ace-window``` from MELPA. If you need me to debug or do some other tests feel free to ask, of course.

**Comment by abo-abo** [comment]
You didn't specify which command you called. Here's my result for `avi-goto-char`:
![ace-window-36](https://cloud.githubusercontent.com/assets/2937359/7470941/9ebf397c-f321-11e4-8058-41e701fed94b.png)

**Comment by manuel-uberti** [comment]
You are right. And, just going through your source made me realise my mistake: ```avi-goto-word-1``` jumps to word start.

All works, then, my bad.
