### ISSUE TITLE
Auto switch to `avi-goto-char` if user enters a punctuation [Feature request]

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/ace-window#38]
I use ace-jump-mode to jump to any point in any window, be it any "word" starting. I double quoted "word" because I use the same `ace-jump-mode` command to jump to even a lone character like the `=` in a line like `a = b +1;`. 

When I tried using `avi-goto-word-1` to do that, it didn't work because it of course does not consider `=` as a word.  Looking into the ace jump mode source, I noticed that probably that package too behaved the same way initially and then the package dev added this option (which happened to be enabled by default):

```el
(defvar ace-jump-mode-detect-punc t
  "When this is non-nil, the ace jump word mode will detect the
char that is not alpha or number. Then, if the query char is a
printable punctuaction, we will use char mode to start the ace
jump mode. If it is nil, an error will come up when
non-alpha-number is given under word mode.")
```

Would you please consider implement this feature for avi-jump too? It will be helpful to have one command to jump to any word beginning or ANY printable char visible in a window that follows a white space in general.

**Comment by abo-abo** [comment]
Let me know if you want to extend the `"[,.+-*/=]"` regex further.

**Comment by kaushalmodi** [comment]
Why not include all printable chars with a known range of ascii values instead of hard-coding the chars? The reason is that some some `` ` `` might be a char they want to jump to and for some `:` might be the char.

From ace jump source:

```el
(defun ace-jump-char-category ( query-char )
  "Detect the type of the char.
For the ascii table, refer to http://www.asciitable.com/

There is four possible return value:
1. 'digit: the number character
2. 'alpha: A-Z and a-z
3. 'punc : all the printable punctuaiton
4. 'other: all the others"
  (cond
   ;; digit
   ((and (>= query-char #x30) (<= query-char #x39))
    'digit)
   ((or
     ;; capital letter
     (and (>= query-char #x41) (<= query-char #x5A))
     ;; lowercase letter
     (and (>= query-char #x61) (<= query-char #x7A)))
    'alpha)
   ((or
     ;; tab
     (equal query-char #x9)
     ;; punc before digit
     (and (>= query-char #x20) (<= query-char #x2F))
     ;; punc after digit before capital letter
     (and (>= query-char #x3A) (<= query-char #x40))
     ;; punc after capital letter before lowercase letter
     (and (>= query-char #x5B) (<= query-char #x60))
     ;; punc after lowercase letter
     (and (>= query-char #x7B) (<= query-char #x7E)))
    'punc)
   (t
    'other)))
```

There's one thing I don't agree with the above ace jump source.. wondering why tab is considered to be a punctuation.

This pull request ( https://github.com/abo-abo/ace-window/pull/40 ) summarizes my thoughts.
