### ISSUE TITLE
push-mark

### ISSUE THREAD

**Issue by Malabarba** [abo-abo/ace-window#41]
I noticed that avi--goto doesn't push the mark before moving. This is a very useful feature of things like `isearch` and `ace-jump` and would be nice to have here.

This is simply a matter of adding `(unless (= pt (point)) (push-mark))` immediately before the `goto-char` in `avi--goto`.

**Comment by abo-abo** [comment]
Thanks for the suggestion.

**Comment by Malabarba** [comment]
This seems to be broken on the latest avy, the mark is not pushed anymore. Has anything changed?

**Comment by abo-abo** [comment]
The previous `avy` behavior did not work across windows. The current one does, but you have to use `avy-pop-mark`.

**Comment by Malabarba** [comment]
Is that command designed to replace pop-mark? Because it doesn't seem to do that for me. Would you like a PR?

**Comment by abo-abo** [comment]
It's supposed to pop mark across buffers. If you can improve it, please go ahead. I use `avy-all-windows` nil, and implemented the functionality for another user that has it at `t`.

**Comment by Malabarba** [comment]
My point is that it simply doesn't pop mark at all. It does something, as in: the point moves *somewhere* but not to the previous place that the mark was. That said I'm actually ok with this command, I don't really need it.

My intent is to ask for the jump commands to `push-mark` as they once did. Pushing mark is the idiomatic Emacs way of marking a previous location before moving the point, so it would integrate better with many people's workflow (I suspect).
Could you make the jump commands `push-mark` (in addition to doing your own tracking)?

**Comment by Malabarba** [comment]
to be more helpful, here's a simplified version of the snippet that isearch uses to push-mark:

    (unless (and transient-mark-mode mark-active)
      (push-mark old-point t))

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by Malabarba** [comment]
Thanks. Works great!
