### ISSUE TITLE
Expanding the Flip keys idea

### ISSUE THREAD

**Issue by joedicastro** [abo-abo/ace-window#44]
The idea of the Flip keys in *ace-window* is a very good idea, and even better to be able to customize them.

But I think that you can expand this idea and make the same with the commands `ace-delete-window` and `ace-maximize-window`, the other main tasks that you could use more. And to be able to customize those keys. (e.g. delete in <kbd>x</kbd> and maximize in <kbd>m</kbd>)

In that way you could use the main row of keys to jump/select a window (asdfghjkl) and the other rows to execute those commands, all from the same initial key binding. Of course, in the same way as already is, that could be customized, so others layouts like *dvorak* and *azerty* could be supported in the same way.

And, even go further, create other commands like:

- `ace-window-split-horizontal` (<kbd>h</kbd>)
- `ace-window-split-vertical`     (<kbd>v</kbd>)

and in this way you can have almost the 90% of the windows managing needs in one key binding + 
one keystroke. Almost perfect.

What do you think about that?

**Comment by abo-abo** [comment]
It's not clear what you're asking. Sounds like you want an `ace-window` hydra, but that's not really related to `ace-window`, since you could make it yourself.

What specific functionality to you want in `ace-window`?

**Comment by joedicastro** [comment]
Well, yes and no... I will explain this in detail later.

**Comment by joedicastro** [comment]
Let me explain this in the best way, visually.

Imagine that we have this window configuration, that we are in the **c** window and we want _jump to/delete_ the **b** window.

![windows](https://cloud.githubusercontent.com/assets/390964/7551363/131977f8-f686-11e4-8900-0578f200d717.png)

So, this are the keys that we could have in `ace-window` (of course, are customizable):

![ace-window](https://cloud.githubusercontent.com/assets/390964/7551375/5c614a3a-f686-11e4-82b0-04a47d874712.png)

No, we gonna suppose that we have a `hydra-window` with this heads:

![hydra-window](https://cloud.githubusercontent.com/assets/390964/7551383/795907ae-f686-11e4-9709-cf692b771f8f.png)

And this is the `ace-window` that I'm proposing to you (of course, all the keys are customizable):

![proposed](https://cloud.githubusercontent.com/assets/390964/7551392/a388a926-f686-11e4-99c9-b788f08c73d4.png)

Thus, we are gonna see now how we would do this operations in those three scenarios:

* jump to **b** window

|ace-window                    | hydra-window                    | proposed                      |
|------------------------------|---------------------------------|-------------------------------|
|<kbd>ace-window binding</kbd> | <kbd>hydra-window binding</kbd> | <kbd>ace-window binding</kbd> |
|<kbd>d</kdb>                  | <kbd>j</kbd>                    | <kbd>d</kdb>                  |
|                              | <kbd>d</kdb>                    |                               |

* delete the **b** window


|ace-window                    | hydra-window                    | proposed                      |
|------------------------------|---------------------------------|-------------------------------|
|<kbd>C-u</kbd>                |                                 |                               |
|<kbd>C-u</kbd>                |                                 |                               |
|<kbd>ace-window binding</kbd> | <kbd>hydra-window binding</kbd> | <kbd>ace-window binding</kbd> |
|<kbd>d</kdb>                  | <kbd>x</kbd>                    | <kbd>x</kdb>                  |
|                              | <kbd>d</kdb>                    | <kbd>d</kdb>                  |

The difference is that if I want to do those operations (splits included) I have to ways to do it:

* Use two different bindings, one for `ace-window` and one for `hydra-window`,
  and have to remember the two and map my brain in two different ways. All of
  that to save a keystroke when I'm only want to jump to a window.

* Use `ace-window` via `hydra-window`, but in this case I have to waste a
  keystroke each time that I want to jump to a window.

The way that I propose is more consistent to all the operations, following the same pattern, and I have only to remember one binding for almost all the day-by-day windows operations.

**Comment by abo-abo** [comment]
Thanks, I see it now. This is indeed a very good idea.  I'd have to re-write a large portion of the package for that, so I don't know how soon this will be available.

Also, nice illustrations. What did you use?

**Comment by joedicastro** [comment]
No need to hurry, I know that some like that would require some refactorization. 

I used Inkscape and then I modified this [*.svg* file][0] from the Wikipedia, 
[0]: http://commons.wikimedia.org/wiki/File:ANSI_Keyboard_Layout_Diagram_with_Form_Factor.svg

**Comment by abo-abo** [comment]
Check if <kbd>x</kbd> works as you wanted.

**Comment by joedicastro** [comment]
I get this error: 

```
if: No such candidate, 120
```

**Comment by abo-abo** [comment]
Make sure to reload the latest avy.el and ace-window.el.

**Comment by joedicastro** [comment]
Right! I didn't updated the `avy` package!

Works perfectly fine until I have only two windows, then fails. But, well for a quick fix is fantastic!

**Comment by joedicastro** [comment]
Sorry to bother you again, this works almost perfectly, and I know that lately you have already enough in your plate (there were a lot of issues opened recently), but I want to comment you two points:

* All works well, but when there are only two windows or less it do not responds to the "alternative actions". This make the solution a bit useless, because even when you have only one window you could want to split it in two.

* I think that the actions should be customizable in a list of pairs of key-action, like in hydra, because not all the people uses the *qwerty* keyboard layout, others could use the *dvorak*, *azerty* or a custom one. At the same time not all the people would like to use all the actions, or even use another different ones. Something like:

("x" aw-delete-window)
("m" aw-swap-window)
("v" aw-split-window-vert)
...

What you think about that?

**Comment by joedicastro** [comment]
Well, thank you very much! Now this works very nice. :smile:

I ended up with this configuration:

```emacs
(setq aw-keys   '(?a ?s ?d ?f ?j ?k ?l)
                aw-dispatch-always t
                aw-dispatch-alist
                '((?x aw-delete-window     "Ace - Delete Window")
                  (?c aw-swap-window       "Ace - Swap Window")
                  (?n aw-flip-window)
                  (?v aw-split-window-vert "Ace - Split Vert Window")
                  (?h aw-split-window-horz "Ace - Split Horz Window")
                  (?m delete-other-windows "Ace - Maximize Window")
                  (?g delete-other-windows)
                  (?b balance-windows)
                  (?u winner-undo)
                  (?r winner-redo)))
```

which corresponds with this mapping:

![customized](https://cloud.githubusercontent.com/assets/390964/7575892/eb372712-f838-11e4-8e51-5a53f2cbca3f.png)

And I have to say you, to being able to choose if to execute the action over the current window or to select one is a fucking very good idea! Chapeau! :+1:

**Comment by joedicastro** [comment]
Now, I ended up making all the windows operations through ace-window & hydra combined:

```emacs
(use-package ace-window
          :ensure t
          :defer 1
          :config
          (set-face-attribute 'aw-leading-char-face nil :foreground "deep sky blue" :weight 'bold :height 3.0)
          (set-face-attribute 'aw-mode-line-face nil :inherit 'mode-line-buffer-id :foreground "lawn green")
          (setq aw-keys   '(?a ?s ?d ?f ?j ?k ?l)
                aw-dispatch-always t
                aw-dispatch-alist
                '((?x aw-delete-window     "Ace - Delete Window")
                  (?c aw-swap-window       "Ace - Swap Window")
                  (?n aw-flip-window)
                  (?v aw-split-window-vert "Ace - Split Vert Window")
                  (?h aw-split-window-horz "Ace - Split Horz Window")
                  (?m delete-other-windows "Ace - Maximize Window")
                  (?g delete-other-windows)
                  (?b balance-windows)
                  (?u winner-undo)
                  (?r winner-redo)))

          (when (package-installed-p 'hydra)
            (defhydra hydra-window-size (:color red)
              "Windows size"
              ("h" shrink-window-horizontally "shrink horizontal")
              ("j" shrink-window "shrink vertical")
              ("k" enlarge-window "enlarge vertical")
              ("l" enlarge-window-horizontally "enlarge horizontal"))
            (defhydra hydra-window-frame (:color red)
              "Frame"
              ("f" make-frame "new frame")
              ("x" delete-frame "delete frame"))
            (defhydra hydra-window-scroll (:color red)
              "Scroll other window"
              ("n" joe-scroll-other-window "scroll")
              ("p" joe-scroll-other-window-down "scroll down"))
            (add-to-list 'aw-dispatch-alist '(?w hydra-window-size/body) t)
            (add-to-list 'aw-dispatch-alist '(?o hydra-window-scroll/body) t)
            (add-to-list 'aw-dispatch-alist '(?\; hydra-window-frame/body) t))
          (ace-window-display-mode t))
```

![customized](https://cloud.githubusercontent.com/assets/390964/7583437/86180fa6-f895-11e4-80ef-c24a7bdf9bf6.png)

Thanks for those amazing and empowering packages!

**Comment by abo-abo** [comment]
Cool. Could you make a wiki page in ace-window with this code and picture?

**Comment by joedicastro** [comment]
Of course, right now!

**Comment by teksturi** [comment]
Would it be possible that when opening this almighty window tool hydra shorcuts are displayed right a way. Then I do not have to remember that x deletes window or w goes to hydra-window-size. If this is possible it will be very cool because then I can use hydra with avy too.

**Comment by joedicastro** [comment]
@teksturi of course it would be possible, you only would have to create a hydra for that and then call the hydra instead of calling the `ace-window` command directly.

**Comment by teksturi** [comment]
But I would like that when hydra start it will draw ace-window layout and when I press example a it will jump and close hydra and ace-window. So I think that then I have to call aw--lead-overlay somehow and then hydra will take control and pass controls to ace-window. I have to say that I look this problem quite bit but I do not know how to solve it.

**Comment by joedicastro** [comment]
@teksturi O.K. Give some time and I'll explain you visually. All that you need is there already.

**Comment by joedicastro** [comment]
@teksturi sorry for the delay, I had to do some other things also.

**The approach**

Well, the best way to do this, without touching anything on the code (I'm always try to find workarounds first, before to think in modifying the code, I like it that way, my hacker soul!) is to launch the two commands at the same time (well, without making using of the `async` module, we will launch them in sequence). The problem here is that both, `ace-window` and `hydra`, would try to capture the keys. But, don't worry, there are creative ways to avoid that. First things first, we could use something like this to launch both commands:

```elisp
(progn
  (hydra-window/body)
  (ace-window 0))
```
**The hydra**

Then now we create our hydra, I show you here the `ace-window` & `hydra` configuration that I used here to better understand what I did:

```elisp
(use-package ace-window
          :ensure t
          :defer 1
          :config
          (set-face-attribute 'aw-leading-char-face nil :foreground "deep sky blue" :weight 'bold :height 2.0)
          (set-face-attribute 'aw-mode-line-face nil :inherit 'mode-line-buffer-id :foreground "lawn green")
          (setq aw-keys   '(?a ?s ?d ?f ?j ?k ?l)
                aw-dispatch-always t
                aw-dispatch-alist
                '((?x aw-delete-window     "Ace - Delete Window")
                  (?c aw-swap-window       "Ace - Swap Window")
                  (?n aw-flip-window)
                  (?h aw-split-window-vert "Ace - Split Vert Window")
                  (?v aw-split-window-horz "Ace - Split Horz Window")
                  (?m delete-other-windows "Ace - Maximize Window")
                  (?g delete-other-windows)
                  (?b balance-windows)
                  (?u winner-undo)
                  (?r winner-redo)))

          (when (package-installed-p 'hydra)
            (defhydra hydra-window (:color blue :hint nil :idle 0.4 :timeout 3)
              "
                                                                              ╭────────────┐
                                                                              │ Ace Window │
            ╭─────────────────────────────────────────────────────────────────┴────────────╯
                [^w^] windows size [^r^] winner redo  [^u^] winner undo  [^o^] scroll other
                [^a^] jump window  [^s^] jump window  [^d^] jump window  [^f^] jump window
                [^g^] max. current [^h^] split horz.  [^j^] jump window  [^k^] jump window
                [^l^] jump window  [^;^] swap window  [^x^] del. window  [^c^] swap window
                [^v^] split vert.  [^b^] balance win. [^n^] last window  [^m^] max window
            --------------------------------------------------------------------------------
               ")
            (defhydra hydra-window-size (:color red)
              "Windows size"
              ("h" shrink-window-horizontally "shrink horizontal")
              ("j" shrink-window "shrink vertical")
              ("k" enlarge-window "enlarge vertical")
              ("l" enlarge-window-horizontally "enlarge horizontal"))
            (defhydra hydra-window-frame (:color red)
              "Frame"
              ("f" make-frame "new frame")
              ("x" delete-frame "delete frame"))
            (defhydra hydra-window-scroll (:color red)
              "Scroll other window"
              ("n" joe-scroll-other-window "scroll")
              ("p" joe-scroll-other-window-down "scroll down"))
            (add-to-list 'aw-dispatch-alist '(?w hydra-window-size/body) t)
            (add-to-list 'aw-dispatch-alist '(?o hydra-window-scroll/body) t)
            (add-to-list 'aw-dispatch-alist '(?\; hydra-window-frame/body) t))
          (ace-window-display-mode t)))
```
As you can see there are three interesting things about this hydra:

1. It's a dumb hydra, it does nothing, but serve its purpose as a shortcuts guide. In this way you don't have to worry about capturing the keys. The keys that you'll press are going to be used by `ace-window`.
2. It has a `:idle 0.4` start time established, to allow that `ace-window` would being launched before the `hydra` does its work and exit.
3. It has a `:timeout 3` time, to exit automatically after 3 seconds, time enough to take a look at the shotrcuts to know what key you need to press. Of course, you can customize this. The purpose is avoid to have to press another key to exit the hydra.

**Does this work?**

It does and works well. It's tricky but it's the poor man solution. You can see how it look here:
![ace-window-hydra](https://cloud.githubusercontent.com/assets/390964/20895384/895617c4-bb19-11e6-8e9d-1d43cd31d8ff.png)

Of course you could customize the hydra text as you like, for example I would get rid off of the "jump to window" keys (a, s, d, f, j, k, l), because you already have the `ace-window` hints right there in front of you. And probably would make it more spartan and only with a few rows. But's that up to you.

**A better solution?**

Well, I would like a less intrusive one, like launch the hydra from `ace-window` itself only when you have doubts about which key to press. Perhaps it could be done simple as adding it to the `aw-dispatch-alist` like the other auxiliary hydras and find a way in which `ace-window` would not exit after calling it. But maybe it's over-complicate things (frankly, I still didn't take a look to the code, I have now other things in my plate) only to achieve that.

**Comment by joedicastro** [comment]
@teksturi Did you test it? Did it work for you? Did you like the hack? Was it what you were looking for?
