### ISSUE TITLE
Use ace-window to open buffers

### ISSUE THREAD

**Issue by tuhdo** [abo-abo/ace-window#47]
It is useful if we can open a buffer in a specified window without moving point to that window. Maybe we can add an advice before `switch-to-buffer`, so people can use their preferred buffer switching command?

**Comment by abo-abo** [comment]
Opening buffers and selecting windows is as orthogonal as it gets.  You can use [a hydra](https://github.com/abo-abo/hydra/wiki/Window-Management) to glue them together, but that's user-specific config.

Another option, again user-specific, is to customize `aw-dispatch-alist`.

```elisp
(defun ace-buffer (window)
  (select-window window)
  (call-interactively 'switch-to-buffer))

(setq aw-dispatch-alist
      '((?b ace-buffer "Ace Buffer")))
```

**Comment by tuhdo** [comment]
Not quite what I meant but is also useful. Anyway, I think I will handle this use case with [window-purpose](https://github.com/bmag/emacs-purpose).
