### ISSUE TITLE
avy--remove-leading-chars is not defined when upgrading to 0.9.0

### ISSUE THREAD

**Issue by tsdeng** [abo-abo/ace-window#49]
after upgrading to 0.9.0 I got error saying:
avy--remove-leading-chars is void

**Comment by Lompik** [comment]
i got the same. All you need to do is to update the `ivy` package to the latest version.

**Comment by abo-abo** [comment]
Try to see if there's any outdated `avy.el` on your system and remove it. If `(require 'avy)` loads an outdated file, the function won't be defined.

**Comment by tsdeng** [comment]
I think it's a bug, this package should depends on avy-jump instead of avy.

I fixed it by adding following line to my .emacs file:

(require 'avy-jump)

**Comment by abo-abo** [comment]
> (require 'avy-jump)

avy-jump.el has been merged into avy.el 4 days ago. You should update your package.

**Comment by tsdeng** [comment]
I did update the package to 0.2
Why am I still seeing the problem?

**Comment by tsdeng** [comment]
the navy version specified in ace-window is 0.2.0(the stable release 6 days
ago)....  which does not include the change you are talking about 4 days ago
