### ISSUE TITLE
can't use aw-displatch-alist 

### ISSUE THREAD

**Issue by Lompik** [abo-abo/ace-window#50]
using `ace-window` 0.9.0 I could not get the the dispatch feature to work. I used this configuration :

    (setq aw-keys   '(?a ?s ?d ?f ?j ?k ?l)
		    aw-dispatch-always t
		    aw-dispatch-alist
		    '((?x aw-delete-window     "Ace - Delete Window")
		      (?c aw-swap-window       "Ace - Swap Window")
		      (?n aw-flip-window)
		      (?v aw-split-window-vert "Ace - Split Vert Window")
		      (?h aw-split-window-horz "Ace - Split Horz Window")
		      (?m delete-other-windows "Ace - Maximize Window")
		      (?g delete-other-windows)
		      (?b balance-windows)
		      (?u winner-undo)
		      (?r winner-redo)))
    (global-set-key (kbd "M-p") 'ace-window)
    
However when I hit `M-p x` I got the following message :

    avy-handler-default: No such candidate, 120

What am I missing ?

**Comment by abo-abo** [comment]
> What am I missing ?

Suppose you have 2 windows. To delete the first one, use <kbd>M-p xa</kbd>.  To delete the second one, use <kbd>M-p xs</kbd>.  It seems that you pressed <kbd>M-p xx</kbd> instead.

**Comment by Lompik** [comment]
I do no have the option to type `xa`, `xs` or `xx` (all it does is insert `a`, `s` or `x` respectively in the buffer). With `M-p x` the function exits with the message I cited above.

**Comment by abo-abo** [comment]
With two windows, evaluate this `(funcall (aw-dispatch-default 120) (next-window))`.

**Comment by Lompik** [comment]
this would delete the `next-window` ad expected which made look a little deeper. 

Long story short, the issue solved by re-bytecompiling the `ace-window.el` file.
