### ISSUE TITLE
Allow point to remain in the current window after swapping

### ISSUE THREAD

**Issue by tuhdo** [abo-abo/ace-window#52]
There should be an option to for this behavior. For example, I have 1 big buffer to the left and 2 small buffers to the right, one is another supplementary code buffer and one is a REPL. I want to use `ace-swap-window` to swap my current buffer with the other two buffers when needed to the big buffer for doing some activities; after finishing, I want to swap back with my original code buffer. All without having to move point back to the big window every time I swap.

**Comment by abo-abo** [comment]
> Allow point to remain in the current window after swapping

The point already always remains in the current window after swapping.

**Comment by abo-abo** [comment]
Nevermind, I meant the buffer stays the same. You can customize now.

**Comment by tuhdo** [comment]
Great. Thanks.
