### ISSUE TITLE
Huge letters

### ISSUE THREAD

**Issue by DamienCassou** [abo-abo/ace-window#55]
Currently, letters identifying the windows are really small. Would it be possible to make them much larger (e.g., half of the window)? Something like what [`switch-window`](https://github.com/dimitri/switch-window) is doing:

![switch-window mode](http://tapoueh.org/images/emacs-switch-window.png)

**Comment by abo-abo** [comment]
It's already possible, by just customizing the face:

```elisp
(custom-set-faces
 '(aw-leading-char-face
   ((t (:inherit ace-jump-face-foreground :height 3.0)))))
```

**Comment by DamienCassou** [comment]
great. Thank you. Here is mine:

```emacs
(custom-set-faces
     '(aw-leading-char-face
       ((t (:inherit ace-jump-face-foreground
                     :height 6.0
                     :underline nil
                     :foreground "red")))))
```

**Comment by abo-abo** [comment]
> :inherit ace-jump-face-foreground

You're not required to inherit `ace-jump-face-foreground`, especially if you specify foreground.  I just copy pasted this code from a post I made before.
