### ISSUE TITLE
Add ace-move-window command

### ISSUE THREAD

**Issue by jamienicol** [abo-abo/ace-window#56]
I think this would be a really useful command. I should explain what I want this function to do. If you think of each window as a stack of buffers, then ace-swap-window swaps the top buffers in stacks "a" and "b". ace-move-window, however, only moves a single buffer from stack "a" to "b". Rather than also move a buffer from "b" to "a", it simply leaves the next buffer in the stack visible in window "a".

Technically this can be achieved by calling "switch-to-prev-buffer" on window "a".

[buffer-move](https://github.com/lukhas/buffer-move/) has an option to do this: (setq buffer-move-behavior 'move). But I prefer ace-window's method of selecting a window to windmove/buffer-move.

Thanks for a great package!

**Comment by abo-abo** [comment]
> If you think of each window as a stack of buffers, then ace-swap-window swaps the top buffers in stacks "a" and "b". ace-move-window, however, only moves a single buffer from stack "a" to "b".

I don't get it. I even installed `buffer-move`: with `abc` windows, using `buf-move-up` `c->a` ends up in `cbb`, which isn't that great.

Can you make an explanation of what you want for an example 3 or 4 window config (describe initial state -> `ace-move-window` -> describe final state).

**Comment by jamienicol** [comment]
Yes, in that example it doesn't seem very useful. I'm guessing you only had a few buffers open, which means that the buffer switched to by "switch-to-prev-buffer" has a high chance of being an already visible buffer.

I'll describe a circumstance in which it's really useful. You have windows 123 with buffers ABC, then you do a grep, or magit-status, or compile, etc. Any command that opens another buffer (called D). Say this command opens in window 1. This gives you 1=D, 2=B, 3=C.

But you want to see buffer A at the same time as buffer D, And you want A to be in window 1 because you were happy with your current layout. So you'd call ace-move-window to move the new buffer in to window 3. The end result would by 1=A, 2=B, 3=D.

It can be used as a way to fix it when a popup buffer chooses a different window than the one you wish it had.

Does that explain it okay?

**Comment by abo-abo** [comment]
Thanks, it's an interesting command. But I think I'll continue to just use `switch-buffer` - too much muscle memory there.

You can try your new command with e.g. <kbd>M-p M a</kbd> if you have previously bound `ace-window` to <kbd>M-p</kbd>.

**Comment by jamienicol** [comment]
Thanks!
