### ISSUE TITLE
Ace window fails display and ignore ecb-buffers

### ISSUE THREAD

**Issue by trashofmasters** [abo-abo/ace-window#57]
On Emacs 25, ace-window `20150520.1014` and ECB 2.40 when adding an ECB buffer name to the list `aw-ignored-buffers` ace-window fails to show the characters and update the faces of all windows.

With `(setq aw-ignored-buffers ())` everything works fine
![screen shot 2015-06-19 at 14 08 00](https://cloud.githubusercontent.com/assets/30650/8253998/b69f0764-168c-11e5-8eb8-510e7fe409c0.png)

Notice in the screenshow above that the ace-window character always shifts the first line in the sidebar buffers.

This screenshot shows the consequences of evaluating `(add-to-list 'aw-ignored-buffers ecb-directories-buffer-name)`

![screen shot 2015-06-19 at 14 08 34](https://cloud.githubusercontent.com/assets/30650/8254037/069239d0-168d-11e5-97cd-865ea19d9b95.png)

To be honest if the issue with the one character shift caused by ace-window can be resolved, I would be happy to let ace-window also jump to ECB windows.

**Comment by abo-abo** [comment]
> This screenshot shows the consequences of evaluating (add-to-list 'aw-ignored-buffers ecb-directories-buffer-name)

Make sense, doesn't it? You have only one window besides the ignored ones. Get more windows -> ace-window works.

> To be honest if the issue with the one character shift caused by ace-window can be resolved, I would be happy to let ace-window also jump to ECB windows.

I'm not sure it's possible to overlay a char over an icon. What is ECB anyway? I installed a package `ecb` from MELPA.  Then it has 194 commands. Which one of 194 should I call to get a window list like yours?

**Comment by trashofmasters** [comment]
> I'm not sure it's possible to overlay a char over an icon. What is ECB anyway? I installed a package ecb from MELPA. Then it has 194 commands. Which one of 194 should I call to get a window list like yours?

Sorry for the missing information, I rushed this report during lunch break. Please use `ecb-activate` to setup the windows seen in the examples above.

ECB stands for Emacs Code Browser, it's a package that integrates with programming modes to provide additional feature that make Emacs more of a IDE.

> Make sense, doesn't it? You have only one window besides the ignored ones. Get more windows -> ace-window works.

It might make sense, but I believe it's far from desirable behaviour. In the last screenshot the ECB edit area, i.e. the window which is showing `*scratch*`, doesn't get the neither the character nor the fontification when I press the ace-window key.

Furthermore the focus is then given to the first ECB window in the list. 

It should be pretty straight forward to reproduce, let me know if you need more details, and thanks for the attention.

**Comment by trashofmasters** [comment]
@abo-abo It's interesting, if I save the customisations to `aw-ignored-buffers` and restart Emacs it all works fine :+1: 

I guess this is no longer an issue!

**Comment by trashofmasters** [comment]
> Make sense, doesn't it? You have only one window besides the ignored ones.
I see what you mean now, sorry for the misunderstanding :) 

Thanks for your support.
