### ISSUE TITLE
Inconsistent behavior with `aw-flip-window` and multiple frames

### ISSUE THREAD

**Issue by glucas** [abo-abo/ace-window#61]
The behavior of `aw-flip-window` seems to be inconsistent when there are multiple frames. If I use `ace-window` to jump from one frame to another and then call `aw-flip-window` multiple times, it only works the first time.

The behavior is more noticeable when you have several frames that each have several windows. In this case `aw-flip-window` will pop back to the most recent frame+window the first time but then on subsequent calls will jump to a window in the same frame that had been visited earlier -- rather than the window in the other frame that I just came from. 

What I'd expect is that flip would allow me to repeatedly switch back and forth between two windows, regardless of which frame they are in,.

**Comment by abo-abo** [comment]
Wow, looking at the code I'm surprised it works for one frame. Why would I even use a ring there?  This needs a major rework, maybe tomorrow. Thanks for bringing it up.

**Comment by abo-abo** [comment]
Please check if it works fine now.

**Comment by glucas** [comment]
Yes, works as expected now. Thanks!
