### ISSUE TITLE
embedded window identifier into modeline?

### ISSUE THREAD

**Issue by listx** [abo-abo/ace-window#62]
I like the concept of ace-window, but it feels like it's too much work. Why not have the mode line show a letter, so that ace-window is basically always on? I don't want to type a key combination just to bring up the ace-window candidate letters --- I'd rather have these letters be shown at all time. Because, why not?

Is this possible? Or rather, is it probable that you can implement it into the existing codebase?

**Comment by abo-abo** [comment]
There is `ace-window-display-mode` already.

**Comment by listx** [comment]
Amazing. Thank you and sorry for the noise!
