### ISSUE TITLE
ace-window interferes destructively with ediff

### ISSUE THREAD

**Issue by grimnebulin** [abo-abo/ace-window#64]
I've been running ediff a lot lately, and I often found that after quitting ediff, Emacs completely ignored all subsequent keyboard input.  Mouse input still worked, but I had to quit and restart Emacs to get the keyboard back.

I went to my .emacs file and gradually started commenting out things I'd added recently, and after commenting out the use of ace-window, I no longer observed the keyboard-freezing behavior.

I experimented further and found that jumping back and forth between ediff's tiny control frame and a single larger main frame using ace-window caused no problems.  As soon as I added a third frame and moved around among the three frames, I again saw the keyboard issue.  (This was the setup I had been using originally.)

**Comment by abo-abo** [comment]
Could you give me a step-by-step recipe to reproduce the issue, from starting Emacs to getting into keyboard-freeze state?

**Comment by grimnebulin** [comment]
Sorry about the delay.  After some more experimentation I was able to reliably cause the issue to occur even when running with "emacs -Q".  Apparently it was just a statistical fluctuation that made me think ace-window was the culprit.

**Comment by abo-abo** [comment]
Issue solved:), thanks.
