### ISSUE TITLE
Switch buffer if there is just one window?

### ISSUE THREAD

**Issue by steckerhalter** [abo-abo/ace-window#65]
If there is just one window could calling `ace-window` switch to the most recent buffer?

I do this with:
```cl
 (switch-to-buffer nil)
```

**Comment by abo-abo** [comment]
I'd like to keep switching windows and buffers orthogonal.  However, you can use advice, or define your own function that calls `ace-window`:

```elisp
(defadvice ace-window (around ace-window-sb activate)
  (if (= 1 (length (window-list)))
      (switch-to-buffer nil)
    ad-do-it))
```

**Comment by steckerhalter** [comment]
ok, thanks
