### ISSUE TITLE
cursor in non-selected window can obscure key

### ISSUE THREAD

**Issue by mjhoy** [abo-abo/ace-window#66]
I just wanted to put this issue here in case anyone else was having the same issue for me. If the cursor in a non-selected window happened to be on the first character of that window, the ace-window key that pops up would be rendered in an unreadable face (this happened on multiple themes I used).

See this screenshot for instance:

![screenshot 2015-10-22 12 21 59](https://cloud.githubusercontent.com/assets/106337/10672886/5de07638-78b8-11e5-93d8-d34be04ae5be.png)

In the *help* window at the bottom, which is not selected at the moment, the cursor was left at the top left, and a face that overrides the background I set for ace-window keys makes it unreadable. (There should be a large "g").

To solve this, I used:

```
(setq-default cursor-in-non-selected-windows 'bar)
```

Although I'd love to know if there is a better way.

**Comment by abo-abo** [comment]
What's your Emacs version, theme and value of `cursor-in-non-selected-windows`? I can't reproduce this in my setup.

**Comment by mjhoy** [comment]
I'm building from HEAD, so maybe that's a problem. 25.0.50.1. Original value of `cursor-in-non-selected-windows` was `t`, and theme was `leuven`.

**Comment by mjhoy** [comment]
... and I think `t` meant that it was `hollow` on my set up at least.

**Comment by abo-abo** [comment]
> I'm building from HEAD, so maybe that's a problem. 25.0.50.1. Original value of cursor-in-non-selected-windows was t, and theme was leuven.

Just tried with these settings (HEAD, `leuven`, `cursor-in-non-selected-windows` both nil and t).
In all cases, I can't reproduce the bug.

**Comment by mjhoy** [comment]
Thanks for trying. I'll close, and hopefully if someone else has the problem they will find this. In any case I'm happy with my solution.
