### ISSUE TITLE
Enlarge the leading char

### ISSUE THREAD

**Issue by xuhdev** [abo-abo/ace-window#70]
The leading char IMO is certainly too small... It's probably a good idea to make it larger, e.g., using 4x4 spaces. [switch-window](http://tapoueh.org/emacs/switch-window.html) does this, but the texts are completely hidden, and it also lacks many other useful features that ace-window offers.

**Comment by abo-abo** [comment]
Use <kbd>M-x</kbd> `customize-group ace-window`. You can easily change the font size of `Show Aw Leading Char Face`.

**Comment by manuel-uberti** [comment]
If it helps, this is what I have:
```
(custom-set-faces
   '(aw-leading-char-face
     ((t (:foreground "red" :weight normal :height 1.5)))))
```

**Comment by xuhdev** [comment]
@manuel-uberti Thanks, it works for me. Can I get height to a larger nnumber, such as 3? It does not work for me when the height is 3 - the leading char simply disappears.

**Comment by manuel-uberti** [comment]
3 doesn't work for me either, but 2.5 works.

**Comment by xuhdev** [comment]
Although don't know why, but 2.9 works for me. Thanks for your suggestion!

**Comment by 501st-alpha1** [comment]
This confused me for a bit too. From the Help page for `set-face-attribute`:

> `:height'

> VALUE specifies the relative or absolute height of the font.  An
> absolute height is an integer, and specifies font height in units
> of 1/10 pt.  A relative height is either a floating point number,
> which specifies a scaling factor for the underlying face height;
> or a function that takes a single argument (the underlying face
> height) and returns the new height.  Note that for the `default'
> face, you must specify an absolute height (since there is nothing
> for it to be relative to).

So if you give it the integer `3`, then it will set the height to be 3/10 pt. However, if you give it the floating point number `3.0`, then it will triple the height of the font.

**Comment by xuhdev** [comment]
@501st-alpha1 I see. Thanks for your explanation!
