### ISSUE TITLE
customize ace-window-display-mode face

### ISSUE THREAD

**Issue by plantarum** [abo-abo/ace-window#71]
Hi,

Is it possible to change the face of the target letter that appears on the modeline with `ace-window-display-mode`? I'd like to change the color to make it stand out from the rest of the mode-line.

Thanks!

Tyler

**Comment by abo-abo** [comment]
Yes. Simply use `aw-mode-line-face`. It's present in the `ace-window` customization group, so you can <kbd>M-x</kbd> `customize` `ace-window` and find the face.

**Comment by plantarum** [comment]
Perfect, thanks!
