### ISSUE TITLE
request: support a non-interactive `ace-window`

### ISSUE THREAD

**Issue by r2evans** [abo-abo/ace-window#72]
I'm converting from `window-numbering-mode`, so please forgive me if I'm missing something.

Use-case: single-key switching to specific windows.

`ace-window` does a good job (I think) of dealing with multiple windows, multiple frames, the latter being the selling point for me. However, I'm become accustomed to the one-key switch, ala `M-2` to switch to the second window. (I know that assigning non-default behavior to `M-1`, `M-2`, ... may be blasphemous to emacs, but it's something I like to impose on myself.)

Looking at the code, I want to do something like `(aw-switch-to-window 2)`, but `select-window` really wants a window object of a sort. So I should be able to convert the `(setq window (cond ...` portion of the code into a non-interactive function.

Does this make sense? I "understand" elisp but am not at all proficient, so if you want a PR, it'll likely be ugly/not-robust.

**Comment by abo-abo** [comment]
Your request is out of scope of `ace-window`. If you miss something in `window-numbering-mode`, try to improve that instead.

Here's a bit of code that you can reuse from `ace-window` though:

```elisp
(global-set-key (kbd "M-1")
                (lambda ()
                  (interactive)
                  (select-window
                   (nth 0 (aw-window-list)))))
(global-set-key (kbd "M-2")
                (lambda ()
                  (interactive)
                  (select-window
                   (nth 1 (aw-window-list)))))
(global-set-key (kbd "M-3")
                (lambda ()
                  (interactive)
                  (select-window
                   (nth 2 (aw-window-list)))))
```

**Comment by r2evans** [comment]
That's exactly what I was looking for; whether it's formally offered as a `defun` or here as something I put in my `~/.emacs.d/...` is moot. Thanks!
