### ISSUE TITLE
Feature request: Display bigger characters

### ISSUE THREAD

**Issue by dscole** [abo-abo/ace-window#74]
I think it would be way more effective (at least for me) if instead of displaying a single character in the upper left corner of each buffer you'd display a gigantic character in the middle of each buffer, like what tmux does in display-pane:
[http://blog.linoxide.com/wp-content/uploads/2014/01/tmux_number.png](url)

It looks like someone already borrowed that approach to vim:
https://github.com/t9md/vim-choosewin

Right now I have 3 monitors, each with it's own frame, and every frame can be split into 1,2, 3 or 4 buffers so it's hard for me to know off hand which buffer maps to which key. I really have to see the buffer's character to know what to press. So, right now I really have to strain my eyes to see those character. Having that massive character in the middle of each buffer, would be fantastic I think.

**Comment by abo-abo** [comment]
Emacs font system doesn't work like tmux. A huge char in the middle would warp all text around it.  You can have a huge char in the corner like this:

    (set-face-attribute 'aw-leading-char-face nil :height 400)

And you can then easily see the displacement I'm talking about.

Another solution is `ace-window-display-mode`: shows that chars permanently in each window's mode line.

**Comment by dscole** [comment]
Actually after opening this issue I went ahead and tried to customize that font myself:

` '(aw-leading-char-face ((t (:foreground "chartreuse" :box (:line-width 2 :color "grey75" :style released-button) :height 10.0 :width normal)))))
`

and I find it much more convenient. The only issue I'm having is that sometimes that character doesn't appear in all buffers, I'm not sure exactly why or how to replicate it. Mostly it works fine so I guess you can close this issue.

**Comment by abo-abo** [comment]
OK, open a new issue if you can pinpoint the bug.
