### ISSUE TITLE
ace-window not working for exwm buffer

### ISSUE THREAD

**Issue by QiangF** [abo-abo/ace-window#76]
Hello Sir,
Exwm is a popular window manager using emacs(https://github.com/ch11ng/exwm/wiki). If a buffer is an X window, ace-window can't show the switching character. Can you make the switching string displayed in the mode line? Then maybe it won't blocked by an x window?
Thank you!

**Comment by abo-abo** [comment]
See `ace-window-display-mode`.

**Comment by QiangF** [comment]
Amazing. Thank you!
For people having the same question. Here is the link to the feature anoucement page.
/[http://oremacs.com/2015/03/12/ace-window-display-mode](url)
