### ISSUE TITLE
Question about char assignment behavior for new frame

### ISSUE THREAD

**Issue by eflanigan00** [abo-abo/ace-window#81]
I set the following

    (setq aw-keys '(?a ?s ?d ?f ?j ?k ?l)) 

I have frame#1 with 2 windows with the following characters: 
frame#1   (a | s)

Then I execute new-frame to create frame#2. The characters I see:
frame#1 (s | d)     ;; the characters of the original frame are re-assigned which can be confusing
frame#2 (a)    

I think it is more intuitive the characters were based on the oldest frame so they remain constant on the original frame(s) as you create new ones. I would expect something like:
frame#1 (a | s)    ;; remain unchanged
frame#2 (d)         ;; new frame is assigned new characters

**Comment by abo-abo** [comment]
See if `aw-reverse-frame-list` solves your problem.

**Comment by eflanigan00** [comment]
Yes that is it, thank you so much! 
I put a note on the wiki, feel free to edit accordingly.
