### ISSUE TITLE
[suggestion] when only 1 window left make ace-window switch between 2 latest buffers?

### ISSUE THREAD

**Issue by zeltak** [abo-abo/ace-window#82]
Hi

i saw a cool lisp code today that gave me an idea. If there is only one window displayed, it would be cool if ace-window could swap it with previous buffer. This would add additional functionality to ace-window when working with 1 window :)

thoughts?

best

Z

**Comment by abo-abo** [comment]
It's best left to user config. It's very easy to implement a custom command that does that.

**Comment by zeltak** [comment]
thx, you mean ontop of ace-window or a complete separate elisp? i cant really code so an example starting point would be great if you have time :)

thx!

Z

**Comment by abo-abo** [comment]
(defun my-ace-window (arg)
      (interactive "p")
      (if (= 1 (length (window-list)))
          (next-buffer)
        (ace-window arg)))

    (global-set-key (kbd "M-p") 'my-ace-window)

**Comment by zeltak** [comment]
perfect!

thx alot!

Z
