### ISSUE TITLE
Behavior of cursor-in-non-selected-windows

### ISSUE THREAD

**Issue by eflanigan00** [abo-abo/ace-window#84]
I use the following for non selected windows. I have problems reading the ace window characters when the hollow square is on the first char of the first line.  Is there a way to not display the cursor-in-non-selected-windows when ace-window is called?

`(setq-default cursor-in-non-selected-windows 'hollow)`

**Comment by abo-abo** [comment]
You can advice `aw-select` and let-bind `cursor-in-non-selected-windows` to nil:

```elisp
(define-advice aw-select (:around (fun &rest r) cursor-stuff)
  (let ((cursor-in-non-selected-windows nil))
    (apply fun r)))
```

**Comment by eflanigan00** [comment]
Clean and easy solution that works perfect. Thank you abo-abo!

**Comment by abo-abo** [comment]
You're welcome
