### ISSUE TITLE
Deviation from Emacs terminology

### ISSUE THREAD

**Issue by basil-conto** [abo-abo/ace-window#85]
The built-in Emacs library `lisp/window.el` defines the function `maximize-window`, which makes a given window "as large as possible without deleting any windows."

The `ace-window` package provides a similarly named `ace-maximize-window`, which instead wraps the `window.el` function `delete-other-windows`.

Unless this is an intentional/preferred overloading of the verb "maximize", and if you are open to the suggestion of rewording to something closer to the language of `delete-other-windows`, I would be happy to provide such a pull request.

**Comment by abo-abo** [comment]
> I would be happy to provide such a pull request.

I'm fine with a rename. Just add an obsolete alias to `ace-maximize-window` that's due to get removed in `0.10.0`.
