### ISSUE TITLE
Support side-window

### ISSUE THREAD

**Issue by stakemori** [abo-abo/ace-window#93]
Emacs 26 now supports side-window (`display-buffer-in-side-window`) officially. A typical usage of side-window is something like sidebar in IDE. Sometimes I do not want to select side-windows. In some cases, it would be better for `ace-window` to ignore side-windows. Do you have any plan to support side-window?

**Comment by stakemori** [comment]
`display-buffer-in-side-window` exists over years. But it appears in NEWS in Emacs 26. So I thought it was a new feature. I changed the title.

**Comment by abo-abo** [comment]
Would be an nice addition to `aw-dispatch-alist`. Please open a PR if you can.

**Comment by stakemori** [comment]
Hmm... I'd rather change `aw-window-list`.
For example, if there are only two windows, then `ace-window` is same as `other-window`. If there are one side-window and two normal (non side-window) windows and one of normal windows is selected,
then (usually) I think it would be better to select the other normal window without asking.
So I would like to filter the return value of `aw-window-list` by introducing a new customize variable or a new optional argument.

**Comment by stakemori** [comment]
I am talking about the attached image. The left side-window is for dierd and I would like to select the scratch buffer or ace-window.el buffer without being asked.
![screenshot_2017-07-06_20-06-28](https://user-images.githubusercontent.com/3415357/27925921-c87f573e-6286-11e7-92be-60ef7aec1599.png)

**Comment by rswgnu** [comment]
You can sort of achieve this with the aw-ignored-buffers variable now in ace-window, though it would be better to have an aw-ignored-modes to ignore buffers with particular major-modes.  You can achieve that by writing your own version of the aw-ignored-p function based on what is there now.

**Comment by stakemori** [comment]
@rswgnu, thanks. I already achieved this by `advice`.  Since `other-window` ignores windows that have window parameter `no-other-window` by default, I think `ace-window` should ignore such windows by default.

**Comment by abo-abo** [comment]
> Hmm... I'd rather change aw-window-list.
> For example, if there are only two windows, then ace-window is same as other-window. If there are one side-window and two normal (non side-window) windows and one of normal windows is selected,
> then (usually) I think it would be better to select the other normal window without asking.
> So I would like to filter the return value of aw-window-list by introducing a new customize variable or a new optional argument.

This sounds fine as well, perhaps along with adapting `aw-ignored-buffers`. Please PR if you wish.
