### ISSUE TITLE
adding toggle-window-split

### ISSUE THREAD

**Issue by doctorate75** [abo-abo/ace-window#96]
kannst du bitte diese nette Funktion hizufügen, die heißt „toggle-window-split“ welche auch in diesem Link beschrieben wird, Danke!

https://stackoverflow.com/a/33456622/1288722

**Comment by rswgnu** [comment]
I suggest closing this issue since it is not clear what is desired here.  The existing command referenced by the link only works for frames with 2 windows and is wholly independent of ace-window, i.e. they can be used together.  There is no clear mapping to how one would add a related command to ace-window's dispatch commands.

**Comment by abo-abo** [comment]
@rswgnu Thanks for the message. Initially I agreed with you and wanted to close it. But this implementation was only 4 lines and I kind of like it now, although I rarely use frames.

@doctorate75 Please test.

**Comment by rswgnu** [comment]
Binding ?t creates an incompatibility with my Hyperbole package which has been coded to be compatible with ace-window.  It binds three new ace-window keys, ?t to throw a buffer from one window to another, ?i to insert a listing item into another window, and ?r to replace the selected window’s buffer with another.  I find ?t the most useful.  I would like to keep all these default bindings compatible if we can agree.  The implementation of these commands requires Hyperbole’s extensive smart key handling and ace-window and therefore is part of Hyperbole tather than ace window.

I think transposing is a useful function.  Maybe another key of your choice that resonates with window display control would be better.

**Comment by abo-abo** [comment]
Switching from `?t` to `?T` is fine with me. Does that work for you?

**Comment by rswgnu** [comment]
I guess so.  Maybe I will develop a patch that adds comments indicating the Hyperbole bindings so we don’t trip over this again.

-- Bob
