### ISSUE TITLE
Is it possible to split when show only one window?

### ISSUE THREAD

**Issue by lmdic** [abo-abo/ace-window#97]
When open at least 3 windows I easy can split (vertically or horizontally) selected windows. OK.
But is it possible to split when show only ONE window?

**Comment by abo-abo** [comment]
I use plain <kbd>C-x 2</kbd> and <kbd>C-x 3</kbd>.

See also `aw-dispatch-always`.

**Comment by lmdic** [comment]
Thanks. Here my bindings. It's very comfortably:

```
;; Split windows
(global-unset-key (kbd "C-x 3")) ;; split-window-right
(global-set-key (kbd "M-4") 'split-window-vertically)

(global-unset-key (kbd "C-x 2")) ;; split-window-below
(global-set-key (kbd "M-$") 'split-window-horizontally)
```

**Comment by nickdrozd** [comment]
If you have just one window, then if `aw-dispatch-always` is set to true, the ace-window split commands will automatically split that one window. You can change the keys in `aw-dispatch-alist` to essentially replace the default window commands with ace-window commands:
```
  (setq aw-dispatch-always t)
  (setq aw-dispatch-alist
	'((?0 aw-delete-window " Ace - Delete Window")
	  (?m aw-swap-window " Ace - Swap Window")
	  (?n aw-flip-window)
	  (?2 aw-split-window-vert " Ace - Split Vert Window")
	  (?3 aw-split-window-horz " Ace - Split Horz Window")
	  (?1 delete-other-windows " Ace - Maximize Window")))
```

**Comment by rswgnu** [comment]
Looks like you can close this issue too.

**Comment by abo-abo** [comment]
Looks to be solved, closing.
